/** Textos fixos que ainda não usam chaves i18n estruturadas. */
const UI_LITERALS = {
  "Leads e Vendas": {
    en: "Leads & Sales",
    es: "Leads y Ventas",
    ar: "العملاء المحتملون والمبيعات",
    tr: "Potansiyel Müşteriler ve Satışlar",
  },
  Atividades: {
    en: "Activities",
    es: "Actividades",
    ar: "الأنشطة",
    tr: "Aktiviteler",
  },
  Projetos: {
    en: "Projects",
    es: "Proyectos",
    ar: "المشاريع",
    tr: "Projeler",
  },
  Mais: {
    en: "More",
    es: "Más",
    ar: "المزيد",
    tr: "Daha fazla",
  },
  Empresas: {
    en: "Companies",
    es: "Empresas",
    ar: "الشركات",
    tr: "Şirketler",
  },
  Inventário: {
    en: "Inventory",
    es: "Inventario",
    ar: "المخزون",
    tr: "Envanter",
  },
  Atendimento: {
    en: "Support",
    es: "Atención",
    ar: "الدعم",
    tr: "Destek",
  },
  "Filas & Chatbot": {
    en: "Queues & Chatbot",
    es: "Filas y Chatbot",
    ar: "الطوابير والروبوت",
    tr: "Kuyruklar ve Chatbot",
  },
  "Respostas Rápidas": {
    en: "Quick Replies",
    es: "Respuestas Rápidas",
    ar: "الردود السريعة",
    tr: "Hızlı Yanıtlar",
  },
  "Agente IA": {
    en: "AI Agent",
    es: "Agente IA",
    ar: "وكيل الذكاء الاصطناعي",
    tr: "Yapay Zeka Ajanı",
  },
  Integrações: {
    en: "Integrations",
    es: "Integraciones",
    ar: "التكاملات",
    tr: "Entegrasyonlar",
  },
  Automações: {
    en: "Automations",
    es: "Automatizaciones",
    ar: "الأتمتة",
    tr: "Otomasyonlar",
  },
  Configurações: {
    en: "Settings",
    es: "Configuración",
    ar: "الإعدادات",
    tr: "Ayarlar",
  },
  Início: {
    en: "Home",
    es: "Inicio",
    ar: "الرئيسية",
    tr: "Início",
  },
  Email: {
    en: "Email",
    es: "Correo",
    ar: "البريد",
    tr: "E-posta",
  },
  Dashboard: {
    en: "Dashboard",
    es: "Panel",
    ar: "لوحة التحكم",
    tr: "Kontrol Paneli",
  },
  Campanhas: {
    en: "Campaigns",
    es: "Campañas",
    ar: "الحملات",
    tr: "Kampanyalar",
  },
  Conexões: {
    en: "Connections",
    es: "Conexiones",
    ar: "الاتصالات",
    tr: "Bağlantılar",
  },
  Contatos: {
    en: "Contacts",
    es: "Contactos",
    ar: "جهات الاتصال",
    tr: "Kişiler",
  },
  Calendário: {
    en: "Calendar",
    es: "Calendario",
    ar: "التقويم",
    tr: "Takvim",
  },
  Relatórios: {
    en: "Reports",
    es: "Informes",
    ar: "التقارير",
    tr: "Raporlar",
  },
  Usuários: {
    en: "Users",
    es: "Usuarios",
    ar: "المستخدمون",
    tr: "Kullanıcılar",
  },
  Ajuda: {
    en: "Help",
    es: "Ayuda",
    ar: "المساعدة",
    tr: "Yardım",
  },
  Salvar: {
    en: "Save",
    es: "Guardar",
    ar: "حفظ",
    tr: "Kaydet",
  },
  Cancelar: {
    en: "Cancel",
    es: "Cancelar",
    ar: "إلغاء",
    tr: "İptal",
  },
  Excluir: {
    en: "Delete",
    es: "Eliminar",
    ar: "حذف",
    tr: "Sil",
  },
  Editar: {
    en: "Edit",
    es: "Editar",
    ar: "تعديل",
    tr: "Düzenle",
  },
  Adicionar: {
    en: "Add",
    es: "Agregar",
    ar: "إضافة",
    tr: "Ekle",
  },
  Buscar: {
    en: "Search",
    es: "Buscar",
    ar: "بحث",
    tr: "Ara",
  },
  "Buscar...": {
    en: "Search...",
    es: "Buscar...",
    ar: "بحث...",
    tr: "Ara...",
  },
  Novo: {
    en: "New",
    es: "Nuevo",
    ar: "جديد",
    tr: "Yeni",
  },
  Criar: {
    en: "Create",
    es: "Crear",
    ar: "إنشاء",
    tr: "Oluştur",
  },
  Fechar: {
    en: "Close",
    es: "Cerrar",
    ar: "إغلاق",
    tr: "Kapat",
  },
  Confirmar: {
    en: "Confirm",
    es: "Confirmar",
    ar: "تأكيد",
    tr: "Onayla",
  },
  Voltar: {
    en: "Back",
    es: "Volver",
    ar: "رجوع",
    tr: "Geri",
  },
  Próximo: {
    en: "Next",
    es: "Siguiente",
    ar: "التالي",
    tr: "İleri",
  },
  Anterior: {
    en: "Previous",
    es: "Anterior",
    ar: "السابق",
    tr: "Önceki",
  },
  Sim: {
    en: "Yes",
    es: "Sí",
    ar: "نعم",
    tr: "Evet",
  },
  Não: {
    en: "No",
    es: "No",
    ar: "لا",
    tr: "Hayır",
  },
  "Carregando...": {
    en: "Loading...",
    es: "Cargando...",
    ar: "جارٍ التحميل...",
    tr: "Yükleniyor...",
  },
  "Nenhum resultado encontrado": {
    en: "No results found",
    es: "No se encontraron resultados",
    ar: "لم يتم العثور على نتائج",
    tr: "Sonuç bulunamadı",
  },
  Selecione: {
    en: "Select",
    es: "Seleccione",
    ar: "اختر",
    tr: "Seçin",
  },
  Todos: {
    en: "All",
    es: "Todos",
    ar: "الكل",
    tr: "Tümü",
  },
  Ativo: {
    en: "Active",
    es: "Activo",
    ar: "نشط",
    tr: "Aktif",
  },
  Inativo: {
    en: "Inactive",
    es: "Inactivo",
    ar: "غير نشط",
    tr: "Pasif",
  },
  Pendente: {
    en: "Pending",
    es: "Pendiente",
    ar: "قيد الانتظار",
    tr: "Beklemede",
  },
  Concluído: {
    en: "Completed",
    es: "Completado",
    ar: "مكتمل",
    tr: "Tamamlandı",
  },
  "Em andamento": {
    en: "In progress",
    es: "En curso",
    ar: "قيد التنفيذ",
    tr: "Devam ediyor",
  },
  Atrasado: {
    en: "Overdue",
    es: "Atrasado",
    ar: "متأخر",
    tr: "Gecikmiş",
  },
  Hoje: {
    en: "Today",
    es: "Hoy",
    ar: "اليوم",
    tr: "Bugün",
  },
  Ontem: {
    en: "Yesterday",
    es: "Ayer",
    ar: "أمس",
    tr: "Dün",
  },
  Amanhã: {
    en: "Tomorrow",
    es: "Mañana",
    ar: "غداً",
    tr: "Yarın",
  },
  Filtros: {
    en: "Filters",
    es: "Filtros",
    ar: "الفلاتر",
    tr: "Filtreler",
  },
  Exportar: {
    en: "Export",
    es: "Exportar",
    ar: "تصدير",
    tr: "Dışa aktar",
  },
  Importar: {
    en: "Import",
    es: "Importar",
    ar: "استيراد",
    tr: "İçe aktar",
  },
  Atualizar: {
    en: "Refresh",
    es: "Actualizar",
    ar: "تحديث",
    tr: "Yenile",
  },
  Limpar: {
    en: "Clear",
    es: "Limpiar",
    ar: "مسح",
    tr: "Temizle",
  },
  Aplicar: {
    en: "Apply",
    es: "Aplicar",
    ar: "تطبيق",
    tr: "Uygula",
  },
  Detalhes: {
    en: "Details",
    es: "Detalles",
    ar: "التفاصيل",
    tr: "Detaylar",
  },
  Ações: {
    en: "Actions",
    es: "Acciones",
    ar: "الإجراءات",
    tr: "İşlemler",
  },
  Status: {
    en: "Status",
    es: "Estado",
    ar: "الحالة",
    tr: "Durum",
  },
  Nome: {
    en: "Name",
    es: "Nombre",
    ar: "الاسم",
    tr: "Ad",
  },
  Descrição: {
    en: "Description",
    es: "Descripción",
    ar: "الوصف",
    tr: "Açıklama",
  },
  Data: {
    en: "Date",
    es: "Fecha",
    ar: "التاريخ",
    tr: "Tarih",
  },
  Hora: {
    en: "Time",
    es: "Hora",
    ar: "الوقت",
    tr: "Saat",
  },
  Valor: {
    en: "Value",
    es: "Valor",
    ar: "القيمة",
    tr: "Değer",
  },
  Total: {
    en: "Total",
    es: "Total",
    ar: "الإجمالي",
    tr: "Toplam",
  },
  Quantidade: {
    en: "Quantity",
    es: "Cantidad",
    ar: "الكمية",
    tr: "Miktar",
  },
  Responsável: {
    en: "Owner",
    es: "Responsable",
    ar: "المسؤول",
    tr: "Sorumlu",
  },
  Observações: {
    en: "Notes",
    es: "Observaciones",
    ar: "ملاحظات",
    tr: "Notlar",
  },
  Telefone: {
    en: "Phone",
    es: "Teléfono",
    ar: "الهاتف",
    tr: "Telefon",
  },
  "E-mail": {
    en: "Email",
    es: "Correo",
    ar: "البريد الإلكتروني",
    tr: "E-posta",
  },
  Endereço: {
    en: "Address",
    es: "Dirección",
    ar: "العنوان",
    tr: "Adres",
  },
  Cidade: {
    en: "City",
    es: "Ciudad",
    ar: "المدينة",
    tr: "Şehir",
  },
  Estado: {
    en: "State",
    es: "Estado",
    ar: "الولاية",
    tr: "Eyalet",
  },
  País: {
    en: "Country",
    es: "País",
    ar: "البلد",
    tr: "Ülke",
  },
  CEP: {
    en: "ZIP code",
    es: "Código postal",
    ar: "الرمز البريدي",
    tr: "Posta kodu",
  },
  Senha: {
    en: "Password",
    es: "Contraseña",
    ar: "كلمة المرور",
    tr: "Şifre",
  },
  Usuário: {
    en: "User",
    es: "Usuario",
    ar: "المستخدم",
    tr: "Kullanıcı",
  },
  Perfil: {
    en: "Profile",
    es: "Perfil",
    ar: "الملف الشخصي",
    tr: "Profil",
  },
  Sair: {
    en: "Logout",
    es: "Cerrar sesión",
    ar: "تسجيل الخروج",
    tr: "Çıkış",
  },
  Notificações: {
    en: "Notifications",
    es: "Notificaciones",
    ar: "الإشعارات",
    tr: "Bildirimler",
  },
  Mensagens: {
    en: "Messages",
    es: "Mensajes",
    ar: "الرسائل",
    tr: "Mesajlar",
  },
  Arquivos: {
    en: "Files",
    es: "Archivos",
    ar: "الملفات",
    tr: "Dosyalar",
  },
  Tarefas: {
    en: "Tasks",
    es: "Tareas",
    ar: "المهام",
    tr: "Görevler",
  },
  Negócios: {
    en: "Deals",
    es: "Negocios",
    ar: "الصفقات",
    tr: "Anlaşmalar",
  },
  Produtos: {
    en: "Products",
    es: "Productos",
    ar: "المنتجات",
    tr: "Ürünler",
  },
  Clientes: {
    en: "Clients",
    es: "Clientes",
    ar: "العملاء",
    tr: "Müşteriler",
  },
  Pagamento: {
    en: "Payment",
    es: "Pago",
    ar: "الدفع",
    tr: "Ödeme",
  },
  Assinatura: {
    en: "Subscription",
    es: "Suscripción",
    ar: "الاشتراك",
    tr: "Abonelik",
  },
  Planos: {
    en: "Plans",
    es: "Planes",
    ar: "الخطط",
    tr: "Planlar",
  },
  Agente: {
    en: "Agent",
    es: "Agente",
    ar: "الوكيل",
    tr: "Ajan",
  },
  Fluxos: {
    en: "Flows",
    es: "Flujos",
    ar: "التدفقات",
    tr: "Akışlar",
  },
  WhatsApp: {
    en: "WhatsApp",
    es: "WhatsApp",
    ar: "واتساب",
    tr: "WhatsApp",
  },
  Tickets: {
    en: "Tickets",
    es: "Tickets",
    ar: "التذاكر",
    tr: "Talepler",
  },
  Enviar: {
    en: "Send",
    es: "Enviar",
    ar: "إرسال",
    tr: "Gönder",
  },
  Transferir: {
    en: "Transfer",
    es: "Transferir",
    ar: "نقل",
    tr: "Aktar",
  },
  Finalizar: {
    en: "Finish",
    es: "Finalizar",
    ar: "إنهاء",
    tr: "Bitir",
  },
  Reabrir: {
    en: "Reopen",
    es: "Reabrir",
    ar: "إعادة فتح",
    tr: "Yeniden aç",
  },
  Aceitar: {
    en: "Accept",
    es: "Aceptar",
    ar: "قبول",
    tr: "Kabul et",
  },
  Recusar: {
    en: "Decline",
    es: "Rechazar",
    ar: "رفض",
    tr: "Reddet",
  },
  Aguardando: {
    en: "Waiting",
    es: "En espera",
    ar: "في الانتظار",
    tr: "Bekliyor",
  },
  "Em atendimento": {
    en: "In service",
    es: "En atención",
    ar: "قيد الخدمة",
    tr: "Hizmette",
  },
  Resolvido: {
    en: "Resolved",
    es: "Resuelto",
    ar: "تم الحل",
    tr: "Çözüldü",
  },
  Fechado: {
    en: "Closed",
    es: "Cerrado",
    ar: "مغلق",
    tr: "Kapalı",
  },
  Aberto: {
    en: "Open",
    es: "Abierto",
    ar: "مفتوح",
    tr: "Açık",
  },
  Online: {
    en: "Online",
    es: "En línea",
    ar: "متصل",
    tr: "Çevrimiçi",
  },
  Offline: {
    en: "Offline",
    es: "Desconectado",
    ar: "غير متصل",
    tr: "Çevrimdışı",
  },
  Conectado: {
    en: "Connected",
    es: "Conectado",
    ar: "متصل",
    tr: "Bağlı",
  },
  Desconectado: {
    en: "Disconnected",
    es: "Desconectado",
    ar: "غير متصل",
    tr: "Bağlantısı kesildi",
  },
  Erro: {
    en: "Error",
    es: "Error",
    ar: "خطأ",
    tr: "Hata",
  },
  Sucesso: {
    en: "Success",
    es: "Éxito",
    ar: "نجاح",
    tr: "Başarılı",
  },
  Aviso: {
    en: "Warning",
    es: "Aviso",
    ar: "تحذير",
    tr: "Uyarı",
  },
  Obrigatório: {
    en: "Required",
    es: "Obligatorio",
    ar: "مطلوب",
    tr: "Zorunlu",
  },
  Opcional: {
    en: "Optional",
    es: "Opcional",
    ar: "اختياري",
    tr: "İsteğe bağlı",
  },
  Copiar: {
    en: "Copy",
    es: "Copiar",
    ar: "نسخ",
    tr: "Kopyala",
  },
  Visualizar: {
    en: "View",
    es: "Ver",
    ar: "عرض",
    tr: "Görüntüle",
  },
  Ocultar: {
    en: "Hide",
    es: "Ocultar",
    ar: "إخفاء",
    tr: "Gizle",
  },
  "Ver mais": {
    en: "See more",
    es: "Ver más",
    ar: "عرض المزيد",
    tr: "Daha fazla gör",
  },
  "Ver menos": {
    en: "See less",
    es: "Ver menos",
    ar: "عرض أقل",
    tr: "Daha az gör",
  },
  "Carregar mais": {
    en: "Load more",
    es: "Cargar más",
    ar: "تحميل المزيد",
    tr: "Daha fazla yükle",
  },
  Português: {
    en: "Portuguese",
    es: "Portugués",
    ar: "البرتغالية",
    tr: "Portekizce",
  },
  English: {
    en: "English",
    es: "Inglés",
    ar: "الإنجليزية",
    tr: "İngilizce",
  },
  Spanish: {
    en: "Spanish",
    es: "Español",
    ar: "الإسبانية",
    tr: "İspanyolca",
  },
  "Listas de Contatos": {
    en: "Contact Lists",
    es: "Listas de Contactos",
    ar: "قوائم جهات الاتصال",
    tr: "Kişi Listeleri",
  },
  "Contatos da Lista": {
    en: "List Contacts",
    es: "Contactos de la Lista",
    ar: "جهات اتصال القائمة",
    tr: "Liste Kişileri",
  },
  "Relatório de Campanha": {
    en: "Campaign Report",
    es: "Informe de Campaña",
    ar: "تقرير الحملة",
    tr: "Kampanya Raporu",
  },
  "Configuração de Campanhas": {
    en: "Campaign Settings",
    es: "Configuración de Campañas",
    ar: "إعدادات الحملة",
    tr: "Kampanya Ayarları",
  },
  "Criar Novo Ticket": {
    en: "Create New Ticket",
    es: "Crear Nuevo Ticket",
    ar: "إنشاء تذكرة جديدة",
    tr: "Yeni Talep Oluştur",
  },
  "Criar Ticket": {
    en: "Create Ticket",
    es: "Crear Ticket",
    ar: "إنشاء تذكرة",
    tr: "Talep Oluştur",
  },
  "Respostas rapidas": {
    en: "Quick Replies",
    es: "Respuestas Rápidas",
    ar: "الردود السريعة",
    tr: "Hızlı Yanıtlar",
  },
  "Filas e Chatbot": {
    en: "Queues & Chatbot",
    es: "Filas y Chatbot",
    ar: "الطوابير والروبوت",
    tr: "Kuyruklar ve Chatbot",
  },
  "Agente de IA": {
    en: "AI Agent",
    es: "Agente de IA",
    ar: "وكيل الذكاء الاصطناعي",
    tr: "Yapay Zeka Ajanı",
  },
  "Identidade visual": {
    en: "Visual Identity",
    es: "Identidad visual",
    ar: "الهوية البصرية",
    tr: "Görsel Kimlik",
  },
  "Configuracao": {
    en: "Settings",
    es: "Configuración",
    ar: "الإعدادات",
    tr: "Ayarlar",
  },
  "Integracoes": {
    en: "Integrations",
    es: "Integraciones",
    ar: "التكاملات",
    tr: "Entegrasyonlar",
  },
  "Automacoes": {
    en: "Automations",
    es: "Automatizaciones",
    ar: "الأتمتة",
    tr: "Otomasyonlar",
  },
  "Atendimentos": {
    en: "Tickets",
    es: "Atenciones",
    ar: "التذاكر",
    tr: "Talepler",
  },
  "Informativos": {
    en: "Announcements",
    es: "Informativos",
    ar: "الإعلانات",
    tr: "Duyurular",
  },
  "Financeiro": {
    en: "Financial",
    es: "Financiero",
    ar: "المالية",
    tr: "Finansal",
  },
  "Carteiras": {
    en: "Wallets",
    es: "Billeteras",
    ar: "المحافظ",
    tr: "Cüzdanlar",
  },
  "Tags": {
    en: "Tags",
    es: "Etiquetas",
    ar: "الوسوم",
    tr: "Etiketler",
  },
  "Kanban": {
    en: "Kanban",
    es: "Kanban",
    ar: "كانبان",
    tr: "Kanban",
  },
  "API": {
    en: "API",
    es: "API",
    ar: "واجهة برمجة التطبيقات",
    tr: "API",
  },
  "Voltar": {
    en: "Back",
    es: "Volver",
    ar: "رجوع",
    tr: "Geri",
  },
  "Editar campanha": {
    en: "Edit campaign",
    es: "Editar campaña",
    ar: "تعديل الحملة",
    tr: "Kampanyayı düzenle",
  },
  "Nenhum registro": {
    en: "No records",
    es: "Sin registros",
    ar: "لا توجد سجلات",
    tr: "Kayıt yok",
  },
  "Nova mensagem": {
    en: "New message",
    es: "Nuevo mensaje",
    ar: "رسالة جديدة",
    tr: "Yeni mesaj",
  },
  "Como posso ajudar?": {
    en: "How can I help?",
    es: "¿Cómo puedo ayudar?",
    ar: "كيف يمكنني المساعدة؟",
    tr: "Nasıl yardımcı olabilirim?",
  },
  "Pergunte algo ao Brain...": {
    en: "Ask Brain something...",
    es: "Pregunta algo a Brain...",
    ar: "اسأل Brain شيئًا...",
    tr: "Brain'e bir şey sor...",
  },
  "Falando… o texto aparece aqui em tempo real": {
    en: "Speaking… text appears here in real time",
    es: "Hablando… el texto aparece aquí en tiempo real",
    ar: "يتحدث… يظهر النص هنا في الوقت الفعلي",
    tr: "Konuşuyor… metin burada gerçek zamanlı görünür",
  },
  "Criar atividade": {
    en: "Create activity",
    es: "Crear actividad",
    ar: "إنشاء نشاط",
    tr: "Aktivite oluştur",
  },
  Pendentes: {
    en: "Pending",
    es: "Pendientes",
    ar: "معلّقة",
    tr: "Bekleyen",
  },
  "Analisar atividades": {
    en: "Analyze activities",
    es: "Analizar actividades",
    ar: "تحليل الأنشطة",
    tr: "Aktiviteleri analiz et",
  },
  Relatório: {
    en: "Report",
    es: "Informe",
    ar: "تقرير",
    tr: "Rapor",
  },
  "Novo contato": {
    en: "New contact",
    es: "Nuevo contacto",
    ar: "جهة اتصال جديدة",
    tr: "Yeni kişi",
  },
  "Análise de dados": {
    en: "Data analysis",
    es: "Análisis de datos",
    ar: "تحليل البيانات",
    tr: "Veri analizi",
  },
  "Resumo geral": {
    en: "General summary",
    es: "Resumen general",
    ar: "ملخص عام",
    tr: "Genel özet",
  },
  "Criar lead de venda": {
    en: "Create sales lead",
    es: "Crear lead de venta",
    ar: "إنشاء عميل محتمل",
    tr: "Satış lead'i oluştur",
  },
  "Analisar leads": {
    en: "Analyze leads",
    es: "Analizar leads",
    ar: "تحليل العملاء المحتملين",
    tr: "Lead'leri analiz et",
  },
  "Exportar leads": {
    en: "Export leads",
    es: "Exportar leads",
    ar: "تصدير العملاء المحتملين",
    tr: "Lead'leri dışa aktar",
  },
  "Resumo de vendas": {
    en: "Sales summary",
    es: "Resumen de ventas",
    ar: "ملخص المبيعات",
    tr: "Satış özeti",
  },
  "Listar contatos": {
    en: "List contacts",
    es: "Listar contactos",
    ar: "عرض جهات الاتصال",
    tr: "Kişileri listele",
  },
  "Exportar contatos": {
    en: "Export contacts",
    es: "Exportar contactos",
    ar: "تصدير جهات الاتصال",
    tr: "Kişileri dışa aktar",
  },
  Análise: {
    en: "Analysis",
    es: "Análisis",
    ar: "تحليل",
    tr: "Analiz",
  },
  "Listar projetos": {
    en: "List projects",
    es: "Listar proyectos",
    ar: "عرض المشاريع",
    tr: "Projeleri listele",
  },
  "Analisar projetos": {
    en: "Analyze projects",
    es: "Analizar proyectos",
    ar: "تحليل المشاريع",
    tr: "Projeleri analiz et",
  },
  "Tickets abertos": {
    en: "Open tickets",
    es: "Tickets abiertos",
    ar: "تذاكر مفتوحة",
    tr: "Açık talepler",
  },
  Dashboard: {
    en: "Dashboard",
    es: "Panel",
    ar: "لوحة التحكم",
    tr: "Kontrol paneli",
  },
  "Listar conexões": {
    en: "List connections",
    es: "Listar conexiones",
    ar: "عرض الاتصالات",
    tr: "Bağlantıları listele",
  },
  "Criar conexão WhatsApp": {
    en: "Create WhatsApp connection",
    es: "Crear conexión WhatsApp",
    ar: "إنشاء اتصال واتساب",
    tr: "WhatsApp bağlantısı oluştur",
  },
  "Criar conexão Telegram": {
    en: "Create Telegram connection",
    es: "Crear conexión Telegram",
    ar: "إنشاء اتصال تيليجرام",
    tr: "Telegram bağlantısı oluştur",
  },
  "Status geral": {
    en: "Overall status",
    es: "Estado general",
    ar: "الحالة العامة",
    tr: "Genel durum",
  },
  "Análise completa": {
    en: "Full analysis",
    es: "Análisis completo",
    ar: "تحليل كامل",
    tr: "Tam analiz",
  },
  Métricas: {
    en: "Metrics",
    es: "Métricas",
    ar: "المقاييس",
    tr: "Metrikler",
  },
  "Gerar relatório": {
    en: "Generate report",
    es: "Generar informe",
    ar: "إنشاء تقرير",
    tr: "Rapor oluştur",
  },
  "Criar campanha": {
    en: "Create campaign",
    es: "Crear campaña",
    ar: "إنشاء حملة",
    tr: "Kampanya oluştur",
  },
  "Enviar mensagem": {
    en: "Send message",
    es: "Enviar mensaje",
    ar: "إرسال رسالة",
    tr: "Mesaj gönder",
  },
  "Criar produto": {
    en: "Create product",
    es: "Crear producto",
    ar: "إنشاء منتج",
    tr: "Ürün oluştur",
  },
  "Resposta rápida": {
    en: "Quick reply",
    es: "Respuesta rápida",
    ar: "رد سريع",
    tr: "Hızlı yanıt",
  },
  "Pré-visualização": {
    en: "Preview",
    es: "Vista previa",
    ar: "معاينة",
    tr: "Önizleme",
  },
  Compartilhar: {
    en: "Share",
    es: "Compartir",
    ar: "مشاركة",
    tr: "Paylaş",
  },
  Publicar: {
    en: "Publish",
    es: "Publicar",
    ar: "نشر",
    tr: "Yayınla",
  },
  "Novo projeto IDE": {
    en: "New IDE project",
    es: "Nuevo proyecto IDE",
    ar: "مشروع IDE جديد",
    tr: "Yeni IDE projesi",
  },
  "Ver criações": {
    en: "View creations",
    es: "Ver creaciones",
    ar: "عرض الإبداعات",
    tr: "Oluşturmalara git",
  },
  "Projetos IDE": {
    en: "IDE projects",
    es: "Proyectos IDE",
    ar: "مشاريع IDE",
    tr: "IDE projeleri",
  },
  "Fechar projeto IDE": {
    en: "Close IDE project",
    es: "Cerrar proyecto IDE",
    ar: "إغلاق مشروع IDE",
    tr: "IDE projesini kapat",
  },
  "Projeto Brain": {
    en: "Brain project",
    es: "Proyecto Brain",
    ar: "مشروع Brain",
    tr: "Brain projesi",
  },
  "Ocultar chat": {
    en: "Hide chat",
    es: "Ocultar chat",
    ar: "إخفاء الدردشة",
    tr: "Sohbeti gizle",
  },
  "Mostrar chat": {
    en: "Show chat",
    es: "Mostrar chat",
    ar: "إظهار الدردشة",
    tr: "Sohbeti göster",
  },
  "Comece a editar seu projeto": {
    en: "Start editing your project",
    es: "Empieza a editar tu proyecto",
    ar: "ابدأ بتعديل مشروعك",
    tr: "Projenizi düzenlemeye başlayın",
  },
  "Enviar arquivos": {
    en: "Upload files",
    es: "Subir archivos",
    ar: "رفع الملفات",
    tr: "Dosya yükle",
  },
  "Importar pasta": {
    en: "Import folder",
    es: "Importar carpeta",
    ar: "استيراد مجلد",
    tr: "Klasör içe aktar",
  },
  "Arquivos importados.": {
    en: "Files imported.",
    es: "Archivos importados.",
    ar: "تم استيراد الملفات.",
    tr: "Dosyalar içe aktarıldı.",
  },
  "Pasta importada.": {
    en: "Folder imported.",
    es: "Carpeta importada.",
    ar: "تم استيراد المجلد.",
    tr: "Klasör içe aktarıldı.",
  },
  "Nenhum arquivo de texto válido selecionado.": {
    en: "No valid text files selected.",
    es: "No se seleccionaron archivos de texto válidos.",
    ar: "لم يتم تحديد ملفات نصية صالحة.",
    tr: "Geçerli metin dosyası seçilmedi.",
  },
  "Nenhum arquivo de texto válido na pasta.": {
    en: "No valid text files in the folder.",
    es: "No hay archivos de texto válidos en la carpeta.",
    ar: "لا توجد ملفات نصية صالحة في المجلد.",
    tr: "Klasörde geçerli metin dosyası yok.",
  },
  "Projeto atualizado.": {
    en: "Project refreshed.",
    es: "Proyecto actualizado.",
    ar: "تم تحديث المشروع.",
    tr: "Proje güncellendi.",
  },
  "Não foi possível atualizar o projeto.": {
    en: "Could not refresh the project.",
    es: "No se pudo actualizar el proyecto.",
    ar: "تعذر تحديث المشروع.",
    tr: "Proje güncellenemedi.",
  },
  "Nome do arquivo (ex: script.js)": {
    en: "File name (e.g. script.js)",
    es: "Nombre del archivo (ej: script.js)",
    ar: "اسم الملف (مثال: script.js)",
    tr: "Dosya adı (ör. script.js)",
  },
  "Arquivo já existe.": {
    en: "File already exists.",
    es: "El archivo ya existe.",
    ar: "الملف موجود بالفعل.",
    tr: "Dosya zaten var.",
  },
  "Novo arquivo": {
    en: "New file",
    es: "Nuevo archivo",
    ar: "ملف جديد",
    tr: "Yeni dosya",
  },
};

export default UI_LITERALS;
