/**
 * Copyright (c) Visão Business. Todos os direitos reservados.
 * VB Solution CRM — propriedade intelectual da Visão Business.
 * Uso conforme LICENSE na raiz do repositório.
 *
 * Mapeamento Lovable snake_case ↔ API VBSolution camelCase (Contratos).
 */

import {
  getCommissionBaseValue,
  recalculateCommissionState,
} from "./realtyCrm";

/** Lovable snake_case → API camelCase (inclui aliases especiais title/value/dates/notes). */
export const LOVABLE_TO_API = {
  id: "id",
  imobiliaria_id: "companyId",
  titulo: "title",
  cliente: "cliente",
  cliente_telefone: "clienteTelefone",
  cliente_cpf: "clienteCpf",
  cliente_email: "clienteEmail",
  cliente_rg: "clienteRg",
  tipo: "tipo",
  valor: "value",
  status: "status",
  data_inicio: "startDate",
  data_fim: "endDate",
  imovel_id: "imovelId",
  corretor_id: "corretorId",
  inquilino: "inquilino",
  proprietario: "proprietario",
  contrato_url: "contratoUrl",
  vistoria_entrada: "vistoriaEntrada",
  vistoria_video: "vistoriaVideo",
  apolice_seguro: "apoliceSeguro",
  observacoes: "notes",
  created_at: "createdAt",
  updated_at: "updatedAt",
  matricula: "matricula",
  proprietario_id: "proprietarioId",
  indice_correcao: "indiceCorrecao",
  percentual_correcao: "percentualCorrecao",
  data_proxima_correcao: "dataProximaCorrecao",
  dia_vencimento_aluguel: "diaVencimentoAluguel",
  data_vencimento_apolice: "dataVencimentoApolice",
  tipo_garantia: "tipoGarantia",
  contrato_anexo_url: "contratoAnexoUrl",
  apolice_anexo_url: "apoliceAnexoUrl",
  vistoria_anexo_url: "vistoriaAnexoUrl",
  numero_agua: "numeroAgua",
  numero_luz: "numeroLuz",
  inscricao_iptu: "inscricaoIptu",
  canal_origem: "canalOrigem",
  proprietario_telefone: "proprietarioTelefone",
  proprietario_cpf: "proprietarioCpf",
  proprietario_email: "proprietarioEmail",
  proprietario_rg: "proprietarioRg",
  proprietario_banco: "proprietarioBanco",
  proprietario_agencia: "proprietarioAgencia",
  proprietario_conta: "proprietarioConta",
  proprietario_pix: "proprietarioPix",
  comissao_percentual: "comissaoPercentual",
  comissao_valor: "comissaoValor",
  comissao_tipo: "comissaoTipo",
  tem_parceria: "temParceria",
  parceiro_nome: "parceiroNome",
  parceiro_comissao_percentual: "parceiroComissaoPercentual",
  parceiro_comissao_valor: "parceiroComissaoValor",
  captador_nome: "captadorNome",
  captador_telefone: "captadorTelefone",
  captador_comissao_percentual: "captadorComissaoPercentual",
  captador_comissao_valor: "captadorComissaoValor",
  imposto_tipo: "impostoTipo",
  imposto_percentual: "impostoPercentual",
  imposto_valor: "impostoValor",
  corretor_nome: "corretorNome",
  corretor_comissao_percentual: "corretorComissaoPercentual",
  corretor_comissao_valor: "corretorComissaoValor",
  valor_iptu: "valorIptu",
  iptu_parcelado: "iptuParcelado",
  valor_condominio: "valorCondominio",
  condominio_inclui: "condominioInclui",
  inquilino_telefone: "inquilinoTelefone",
  inquilino_cpf: "inquilinoCpf",
  inquilino_email: "inquilinoEmail",
  inquilino_rg: "inquilinoRg",
  inquilino2_nome: "inquilino2Nome",
  inquilino2_cpf: "inquilino2Cpf",
  inquilino2_telefone: "inquilino2Telefone",
  inquilino2_email: "inquilino2Email",
  inquilino2_rg: "inquilino2Rg",
  caucao_valor: "caucaoValor",
  caucao_quantidade: "caucaoQuantidade",
  conjuge_proprietario: "conjugeProprietario",
  conjuge_cpf: "conjugeCpf",
  conjuge_telefone: "conjugeTelefone",
  conjuge_email: "conjugeEmail",
  aditivo_anexo_url: "aditivoAnexoUrl",
  seguro_incendio_anexo_url: "seguroIncendioAnexoUrl",
  seguro_fianca_anexo_url: "seguroFiancaAnexoUrl",
  fiador_nome: "fiadorNome",
  fiador_cpf: "fiadorCpf",
  fiador_telefone: "fiadorTelefone",
  fiador_email: "fiadorEmail",
  fiador_estado_civil: "fiadorEstadoCivil",
  fiador_endereco: "fiadorEndereco",
  fiador_matricula_url: "fiadorMatriculaUrl",
  fiador_renda_url: "fiadorRendaUrl",
  fiador2_nome: "fiador2Nome",
  fiador2_cpf: "fiador2Cpf",
  fiador2_telefone: "fiador2Telefone",
  fiador2_email: "fiador2Email",
  fiador2_estado_civil: "fiador2EstadoCivil",
  fiador2_endereco: "fiador2Endereco",
  fiador2_matricula_url: "fiador2MatriculaUrl",
  fiador2_renda_url: "fiador2RendaUrl",
  vistoria_video_url: "vistoriaVideoUrl",
  caucao_comprovante_url: "caucaoComprovanteUrl",
  comprovante_agua_url: "comprovanteAguaUrl",
  comprovante_luz_url: "comprovanteLuzUrl",
  numero_unidade: "numeroUnidade",
  parceria_envolvidos: "parceriaEnvolvidos",
  codigo_contrato: "codigoContrato",
  lead_sale_id: "leadSaleId",
  proposta_id: "propostaId",
  company_id: "companyId",
};

export const API_TO_LOVABLE = Object.entries(LOVABLE_TO_API).reduce((acc, [snake, camel]) => {
  if (!acc[camel]) acc[camel] = snake;
  return acc;
}, {});

function mapKeys(obj, dictionary) {
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) return obj;
  const out = {};
  Object.keys(obj).forEach((key) => {
    const mapped = dictionary[key] || key;
    out[mapped] = obj[key];
  });
  return out;
}

/** Converte objeto Lovable (snake_case) → payload API (camelCase). */
export function lovableToApi(obj) {
  return mapKeys(obj, LOVABLE_TO_API);
}

/** Converte objeto API (camelCase) → formato Lovable (snake_case). */
export function apiToLovable(obj) {
  return mapKeys(obj, API_TO_LOVABLE);
}

/** Estado inicial do formulário de contrato em camelCase (API). */
export function emptyContratoForm() {
  return {
    title: "",
    cliente: "",
    clienteTelefone: "",
    clienteCpf: "",
    clienteEmail: "",
    clienteRg: "",
    tipo: "Venda",
    value: 0,
    status: "rascunho",
    startDate: "",
    endDate: "",
    imovelId: "",
    corretorId: "",
    proprietarioId: "",
    inquilino: "",
    proprietario: "",
    vistoriaEntrada: false,
    vistoriaVideo: false,
    apoliceSeguro: false,
    notes: "",
    matricula: "",
    indiceCorrecao: "IGPM",
    percentualCorrecao: 0,
    dataProximaCorrecao: "",
    diaVencimentoAluguel: 10,
    dataVencimentoApolice: "",
    tipoGarantia: "seguro_fianca",
    contratoAnexoUrl: "",
    apoliceAnexoUrl: "",
    vistoriaAnexoUrl: "",
    numeroAgua: "",
    numeroLuz: "",
    inscricaoIptu: "",
    canalOrigem: "",
    parceriaEnvolvidos: [],
    proprietarioTelefone: "",
    proprietarioCpf: "",
    proprietarioEmail: "",
    proprietarioRg: "",
    proprietarioBanco: "",
    proprietarioAgencia: "",
    proprietarioConta: "",
    proprietarioPix: "",
    comissaoPercentual: 0,
    comissaoValor: 0,
    comissaoTipo: "mensal",
    temParceria: false,
    parceiroNome: "",
    parceiroComissaoPercentual: 0,
    parceiroComissaoValor: 0,
    captadorNome: "",
    captadorTelefone: "",
    captadorComissaoPercentual: 0,
    captadorComissaoValor: 0,
    impostoTipo: "",
    impostoPercentual: 0,
    impostoValor: 0,
    corretorNome: "",
    corretorComissaoPercentual: 0,
    corretorComissaoValor: 0,
    valorIptu: 0,
    iptuParcelado: false,
    valorCondominio: 0,
    condominioInclui: "",
    inquilinoTelefone: "",
    inquilinoCpf: "",
    inquilinoEmail: "",
    inquilinoRg: "",
    inquilino2Nome: "",
    inquilino2Cpf: "",
    inquilino2Telefone: "",
    inquilino2Email: "",
    inquilino2Rg: "",
    caucaoValor: 0,
    caucaoQuantidade: 1,
    conjugeProprietario: "",
    conjugeCpf: "",
    conjugeTelefone: "",
    conjugeEmail: "",
    fiadorMatriculaUrl: "",
    caucaoComprovanteUrl: "",
    vistoriaVideoUrl: "",
    aditivoAnexoUrl: "",
    seguroIncendioAnexoUrl: "",
    seguroFiancaAnexoUrl: "",
    fiadorNome: "",
    fiadorCpf: "",
    fiadorTelefone: "",
    fiadorEmail: "",
    fiadorEstadoCivil: "",
    fiadorEndereco: "",
    fiadorRendaUrl: "",
    fiador2Nome: "",
    fiador2Cpf: "",
    fiador2Telefone: "",
    fiador2Email: "",
    fiador2EstadoCivil: "",
    fiador2Endereco: "",
    fiador2MatriculaUrl: "",
    fiador2RendaUrl: "",
    comprovanteAguaUrl: "",
    comprovanteLuzUrl: "",
    numeroUnidade: "",
    codigoContrato: "",
    contratoUrl: "",
  };
}

export { getCommissionBaseValue, recalculateCommissionState };
