# -*- coding: utf-8 -*-
"""Gera os 5 HTMLs de treinamento com 50 páginas densas cada."""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pdf_kit import a, cover, write_doc, TOTAL, code as code_html, callout
from page_factory import dense, ensure_count, pack


def P(k, t, lead, why, how, impact, steps, **kw):
    return (k, t, dense(lead, why, how, impact, steps, **kw))


# ---------------------------------------------------------------------------
# DOC 02 VERCEL
# ---------------------------------------------------------------------------
def doc_vercel():
    M = "Frontend · Vercel"
    pages = [
        P("Mapa", "Sumário · o que este manual resolve",
          "Aqui você publica só o painel React. A API continua na Railway/VPS.",
          "Colocar o CRM no ar com URL pública para o time usar.",
          "Build na Vercel com REACT_APP_BACKEND_URL apontando para a API.",
          "Sem isso o time só acessa localhost. API na Vercel quebra WhatsApp.",
          [("Passo 1", "Entenda a regra: Vercel = painel."),
           ("Passo 2", "Prepare a URL da API (Railway/VPS) antes do build."),
           ("Passo 3", "Siga conta → import → Root Directory → env → deploy."),
           ("Passo 4", "Alinhe FRONTEND_URL na API e teste login."),
           ("Passo 5", "Só então domínio próprio."),
           ("Passo 6", "Use o checklist go-live no fim.")],
          tbl=(["Bloco", "Páginas"], [["Conceito e build local", "3–10"], ["Vercel passo a passo", "11–22"],
                ["CORS e domínio", "23–30"], ["Alternativas", "31–36"], ["Prompts e go-live", "37–50"]]),
          links=[("Vercel", "https://vercel.com")],
          note="<strong>Regra de ouro</strong><br/>Nunca Root Directory = backend na Vercel."),

        P("Regra", "Regra de ouro · Vercel não hospeda a API",
          "A Vercel é ótima para front estático/SPA. Não é lugar de Baileys, Bull e Socket 24h.",
          "Evitar arquitetura errada no primeiro deploy.",
          "Painel chama REACT_APP_BACKEND_URL. Processos longos ficam na API.",
          "API na Vercel = timeout, frio, WhatsApp instável.",
          [("Passo 1", "Escreva no papel: painel = Vercel · API = Railway/VPS."),
           ("Passo 2", "Confirme que já tem BACKEND_URL HTTPS da API."),
           ("Passo 3", "Se ainda não tem API, pause e abra o PDF VPS/Railway."),
           ("Passo 4", "Não crie projeto Vercel com root na pasta backend."),
           ("Passo 5", "Não cole JWT, DATABASE_URL ou Redis na Vercel."),
           ("Passo 6", "Siga para o build local de teste.")],
          checks=["Sei a URL da API", "Não vou colocar backend na Vercel"],
          note="<strong>Onde acarreta</strong><br/>Time pergunta “por que o WhatsApp cai” → quase sempre API no lugar errado.", note_kind="warn"),

        P("Peças", "O que é frontend neste CRM",
          "Frontend é a pasta frontend: React (Create React App) com telas de login, tickets e menus.",
          "Entregar a interface que o corretor usa no Chrome.",
          "npm run build gera a pasta build. A Vercel serve esses arquivos e faz rewrite SPA.",
          "Build com localhost = produção ainda tenta falar com seu PC.",
          [("Passo 1", "Abra VBSOLUTIONCRMCodigoFonte-main/frontend no explorer."),
           ("Passo 2", "Confira package.json e script build."),
           ("Passo 3", "Localize .env.example ou .env.development."),
           ("Passo 4", "Anote: Output Directory = build."),
           ("Passo 5", "Anote: Framework = Create React App."),
           ("Passo 6", "Root Directory no deploy = VBSOLUTIONCRMCodigoFonte-main/frontend.")],
          tbl=(["Item", "Valor"], [["Pasta", "frontend"], ["Build", "npm run build"], ["Saída", "build"], ["Node", "20.x"]]),
          links=[("Repo", "https://github.com/visaobusinesstech/codigo-fonte-COUTINHO")]),

        P("Build local", "Build local · ensaiar antes da Vercel",
          "Rodar o build no PC mostra erro de lint/env antes de queimar minuto de deploy.",
          "Validar que o pacote nasce com a URL certa da API.",
          "REACT_APP_* são gravados no JS no momento do build.",
          "Errar aqui e só descobrir na Vercel atrasa o go-live.",
          [("Passo 1", "cd VBSOLUTIONCRMCodigoFonte-main/frontend"),
           ("Passo 2", "copy .env.example .env  (ou edite .env.production.local)"),
           ("Passo 3", "Defina REACT_APP_BACKEND_URL=https://SUA-API sem barra final"),
           ("Passo 4", "npm install"),
           ("Passo 5", "npm run build"),
           ("Passo 6", "Se falhar, leia o erro (CI/eslint) antes de ir à Vercel")],
          code_block="REACT_APP_BACKEND_URL=https://SEU-SERVICO.up.railway.app\nDISABLE_ESLINT_PLUGIN=true\nCI=false\nGENERATE_SOURCEMAP=false",
          checks=["build terminou", "pasta build existe"]),

        P("REACT_APP", "REACT_APP_BACKEND_URL · para que serve",
          "É o endereço que o painel usa em toda chamada de API.",
          "Ligar o browser à API pública correta.",
          "CRA embute a variável no bundle. Runtime da Vercel não relê sozinho sem rebuild.",
          "Valor localhost em Production = Network no F12 mostra localhost e login falha fora do seu PC.",
          [("Passo 1", "Copie a URL HTTPS da API (Railway/VPS)."),
           ("Passo 2", "Remova barra no final se houver."),
           ("Passo 3", "Cole em REACT_APP_BACKEND_URL na Vercel (Production e Preview)."),
           ("Passo 4", "Dispare Redeploy depois de mudar."),
           ("Passo 5", "Abra o site → F12 → Network → confira o host das chamadas."),
           ("Passo 6", "Se ainda for localhost, o build antigo está no ar: redeploy de novo.")],
          note="<strong>Como funciona</strong><br/>Mudar Variable sem Redeploy não reescreve o JS já publicado.", note_kind="warn"),

        P("Conta", "Criar conta Vercel e conectar GitHub",
          "A Vercel puxa o código do GitHub e builda a cada push (se habilitado).",
          "Ter um lugar oficial para o painel.",
          "OAuth GitHub autoriza o import do repo.",
          "Sem autorização o repo privado não aparece na lista.",
          [("Passo 1", "Abra https://vercel.com e Continue with GitHub."),
           ("Passo 2", "Autorize o acesso à organização/repo do código-fonte."),
           ("Passo 3", "Confirme o e-mail se pedir."),
           ("Passo 4", "Entre no Dashboard."),
           ("Passo 5", "Deixe o cartão/plano conforme a conta (Hobby serve para começar)."),
           ("Passo 6", "Siga para Import Project.")],
          links=[("Vercel", "https://vercel.com"), ("GitHub repo", "https://github.com/visaobusinesstech/codigo-fonte-COUTINHO")],
          checks=["Login ok", "Repo visível ou ZIP/upload alternativo combinado"]),

        P("Import", "Importar o repositório na Vercel",
          "New Project → Import lista os repos que o GitHub liberou.",
          "Criar o projeto ligado ao código certo.",
          "Cada import vira um Project com deploys.",
          "Importar o repo errado builda outra coisa.",
          [("Passo 1", "Dashboard → Add New → Project."),
           ("Passo 2", "Ache codigo-fonte-COUTINHO (ou o nome do fork/cliente)."),
           ("Passo 3", "Clique Import."),
           ("Passo 4", "Ainda não aperte Deploy: configure Root e Env antes."),
           ("Passo 5", "Se não aparece, GitHub → Settings → Applications → Vercel → Repository access."),
           ("Passo 6", "Volte e atualize a lista.")],
          note="<strong>Onde acarreta</strong><br/>Repo sem acesso = tela vazia e sensação de “sumiu o código”."),

        P("Root", "Root Directory do frontend",
          "No monorepo a Vercel precisa saber qual pasta buildar.",
          "Apontar para o package.json do painel.",
          "Root Directory = VBSOLUTIONCRMCodigoFonte-main/frontend",
          "Root na raiz ou no backend = Cannot find package.json / build errado.",
          [("Passo 1", "Em Configure Project, abra Root Directory."),
           ("Passo 2", "Edit → navegue até VBSOLUTIONCRMCodigoFonte-main/frontend."),
           ("Passo 3", "Salve."),
           ("Passo 4", "Framework Preset: Create React App (ou Other)."),
           ("Passo 5", "Build Command: npm run build"),
           ("Passo 6", "Output Directory: build · Install: npm install")],
          code_block="Root Directory: VBSOLUTIONCRMCodigoFonte-main/frontend\nBuild: npm run build\nOutput: build",
          checks=["Root = frontend", "Output = build"]),

        P("Node20", "Node 20 na Vercel",
          "O CRM espera Node 20. Versão antiga quebra dependências.",
          "Build previsível igual ao local.",
          "Settings → General → Node.js Version = 20.x",
          "Node 18/16 pode falhar em pacotes novos.",
          [("Passo 1", "Project → Settings → General."),
           ("Passo 2", "Node.js Version → 20.x"),
           ("Passo 3", "Salve."),
           ("Passo 4", "Faça Redeploy do último deployment."),
           ("Passo 5", "Nos logs, confirme versão do Node no início do build."),
           ("Passo 6", "Alinhe com o node -v do seu PC (v20).")],
          links=[("Node.js", "https://nodejs.org")],
          note="<strong>Como funciona</strong><br/>A Vercel usa a versão configurada no projeto, não a do seu notebook, no build da nuvem."),

        P("Env Vercel", "Environment Variables na Vercel · o pacote certo",
          "Só variáveis que o React pode ver (REACT_APP_*) e flags de build.",
          "Build sem surpresa de eslint/CI e API apontada.",
          "Production e Preview devem ter as mesmas chaves críticas.",
          "Colocar segredo de banco aqui vaza no browser se prefixado errado.",
          [("Passo 1", "Settings → Environment Variables."),
           ("Passo 2", "REACT_APP_BACKEND_URL = https://SUA-API"),
           ("Passo 3", "DISABLE_ESLINT_PLUGIN = true"),
           ("Passo 4", "CI = false"),
           ("Passo 5", "GENERATE_SOURCEMAP = false"),
           ("Passo 6", "Marque Production e Preview · Save · Redeploy")],
          tbl=(["Nome", "Valor", "Por quê"],
               [["REACT_APP_BACKEND_URL", "https://api...", "Chamadas do painel"],
                ["DISABLE_ESLINT_PLUGIN", "true", "Lint não derruba build"],
                ["CI", "false", "Warning não vira erro"],
                ["GENERATE_SOURCEMAP", "false", "Build menor"]]),
          note="<strong>Não coloque</strong><br/>JWT, DATABASE_URL, REDIS_*, STRIPE_SECRET.", note_kind="danger"),

        P("Proibido", "O que nunca vai na Vercel",
          "Segredos de servidor não pertencem ao front.",
          "Reduzir vazamento e confusão de arquitetura.",
          "Browser baixa o JS. Tudo que for REACT_APP_ pode vazar.",
          "Segredo na Vercel “porque era mais fácil” = incidente de segurança.",
          [("Passo 1", "Revise a lista de Variables."),
           ("Passo 2", "Apague qualquer DB_*, JWT_*, REDIS_*, STRIPE_SECRET."),
           ("Passo 3", "Mantenha só REACT_APP_* e flags de build."),
           ("Passo 4", "Segredos ficam na Railway/VPS."),
           ("Passo 5", "Se já vazou, rode chaves novas na API."),
           ("Passo 6", "Avise o time para não recolocar.")],
          checks=["Nenhum segredo de servidor na Vercel", "API tem os segredos"]),

        P("vercel.json", "vercel.json e rewrite SPA",
          "Rotas como /tickets/123 precisam voltar para index.html.",
          "F5 em rota interna não dar 404.",
          "Rewrites mandam tudo para index.html; o React Router resolve.",
          "Sem rewrite: link direto e refresh quebram em produção.",
          [("Passo 1", "Abra frontend/vercel.json no código."),
           ("Passo 2", "Confirme o rewrite abaixo."),
           ("Passo 3", "Se não existir, crie o arquivo e faça commit."),
           ("Passo 4", "Deploy de novo."),
           ("Passo 5", "Teste: entre numa rota interna e aperte F5."),
           ("Passo 6", "404 = rewrite ausente ou Output Directory errado.")],
          code_block='{\n  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]\n}',
          note="<strong>Como funciona</strong><br/>CDN entrega index.html; o JS lê a URL e mostra a tela certa."),

        P("Deploy", "Primeiro Deploy · ler logs",
          "Deploy gera URL *.vercel.app. Logs mostram se o build passou.",
          "Sair do “configurado” para “no ar”.",
          "Install → build → upload da pasta build.",
          "Erro de Root/env aparece aqui, não no Chrome ainda.",
          [("Passo 1", "Clique Deploy (ou Redeploy)."),
           ("Passo 2", "Abra Building e acompanhe."),
           ("Passo 3", "Se falhar em eslint/CI, confira Variables CI=false."),
           ("Passo 4", "Se falhar package.json, confira Root Directory."),
           ("Passo 5", "Sucesso: copie a URL Production."),
           ("Passo 6", "Abra a URL e vá para o teste de login (depois do CORS).")],
          checks=["Deploy Ready", "URL anotada"]),

        P("CORS", "CORS · FRONTEND_URL na API",
          "O browser bloqueia chamada se a API não reconhecer a origem do painel.",
          "Login e menus falando com a API sem erro de CORS.",
          "API compara Origin com FRONTEND_URL (e às vezes WEB_ORIGIN).",
          "URL com barra, http vs https ou preview diferente = bloqueio.",
          [("Passo 1", "Copie a URL do painel exatamente como o Chrome mostra."),
           ("Passo 2", "Na API: FRONTEND_URL=essa URL sem / final."),
           ("Passo 3", "Se precisar, WEB_ORIGIN com o mesmo valor."),
           ("Passo 4", "Redeploy/pm2 restart na API."),
           ("Passo 5", "No painel, F12 → Console: sumiu o erro CORS?"),
           ("Passo 6", "Teste login de novo.")],
          note="<strong>Onde acarreta</strong><br/>Painel “abre” mas botões não salvam: quase sempre CORS ou REACT_APP errado.", note_kind="warn"),

        P("Teste login", "Testar login e Network no F12",
          "Prova real: usuário entra e as requests vão para a API certa.",
          "Validar build + CORS + usuário admin.",
          "Network mostra host, status e payload.",
          "Achar “bonito mas morto” sem F12 perde tempo.",
          [("Passo 1", "Abra o painel na URL Vercel."),
           ("Passo 2", "F12 → Network → preserve log."),
           ("Passo 3", "Faça login com o admin do banco/seed."),
           ("Passo 4", "Ache a request de auth: host deve ser a API."),
           ("Passo 5", "Status 200/201 e redirecionamento ao dashboard."),
           ("Passo 6", "Se host for localhost, volte à Variable e Redeploy.")],
          checks=["Login ok", "Host da API correto", "Sem CORS no Console"]),

        P("Preview", "Preview vs Production",
          "Cada branch/PR pode ter URL preview. Production é a principal.",
          "Testar mudança sem derrubar o link do cliente.",
          "Variables podem divergir por ambiente se você marcar só um.",
          "Preview com API de produção mistura teste e dado real.",
          [("Passo 1", "Marque Variables críticas em Production e Preview."),
           ("Passo 2", "Ideal: API de homolog para Preview."),
           ("Passo 3", "FRONTEND_URL da API de homolog = URL preview."),
           ("Passo 4", "Não teste WhatsApp real no preview sem querer."),
           ("Passo 5", "Promova para Production só após checklist."),
           ("Passo 6", "Documente qual URL o cliente usa.")],
          note="<strong>Como funciona</strong><br/>Mesmo código, URLs diferentes. O perigo é Variable pela metade."),

        P("Redeploy", "Quando mudar variável · Redeploy obrigatório",
          "REACT_APP_* não é lida a cada request; entra no build.",
          "Aplicar URL nova da API de verdade.",
          "Redeploy roda install/build de novo com Variables atuais.",
          "Só Save na Variable = site antigo continua no ar.",
          [("Passo 1", "Altere REACT_APP_BACKEND_URL."),
           ("Passo 2", "Deployments → ⋮ → Redeploy."),
           ("Passo 3", "Espere Ready."),
           ("Passo 4", "Hard refresh no Chrome (Ctrl+F5)."),
           ("Passo 5", "F12 Network de novo."),
           ("Passo 6", "Atualize FRONTEND_URL na API se a URL do painel mudou.")],
          checks=["Redeploy feito", "Network mostra host novo"]),

        P("Domínio", "Domínio próprio na Vercel",
          "Trocar *.vercel.app por crm.suaempresa.com.",
          "Marca própria no Chrome do cliente.",
          "DNS CNAME para cname.vercel-dns.com + Domain na Vercel.",
          "Esquecer FRONTEND_URL = CORS no dia da virada.",
          [("Passo 1", "Project → Settings → Domains → Add."),
           ("Passo 2", "Digite crm.suaempresa.com."),
           ("Passo 3", "No DNS, CNAME conforme a Vercel mostrar."),
           ("Passo 4", "Espere Valid."),
           ("Passo 5", "Atualize FRONTEND_URL na API para o domínio novo."),
           ("Passo 6", "Teste login e F5 em rota interna.")],
          links=[("Docs Domains Vercel", "https://vercel.com/docs/domains")],
          note="<strong>Onde acarreta</strong><br/>Webhook Meta não usa o domínio do painel; usa o da API. Mas CORS sim usa o do painel."),

        P("Quatro URLs", "As 4 URLs que precisam bater",
          "Um desenho mental evita 90% dos bugs de “não conecta”.",
          "Alinhar front e API depois de qualquer mudança de domínio.",
          "Quatro variáveis em dois mundos.",
          "Uma desatualizada quebra login ou webhook.",
          [("Passo 1", "Anote REACT_APP_BACKEND_URL (Vercel)."),
           ("Passo 2", "Anote BACKEND_URL (API)."),
           ("Passo 3", "Anote PUBLIC_BACKEND_URL (API/Meta)."),
           ("Passo 4", "Anote FRONTEND_URL (API/CORS)."),
           ("Passo 5", "Compare no Bloco de Notas: sem / final, https certo."),
           ("Passo 6", "Redeploy front e API após correção.")],
          tbl=(["Variável", "Onde"],
               [["REACT_APP_BACKEND_URL", "Vercel"],
                ["BACKEND_URL", "API"],
                ["PUBLIC_BACKEND_URL", "API"],
                ["FRONTEND_URL", "API"]])),

        P("Netlify", "Alternativa · Netlify",
          "Mesma ideia: build do frontend e publish da pasta build.",
          "Opção se o time já usa Netlify.",
          "Base directory frontend + redirects SPA.",
          "Esquecer redirect = 404 no F5.",
          [("Passo 1", "New site from Git · mesmo repo."),
           ("Passo 2", "Base: VBSOLUTIONCRMCodigoFonte-main/frontend"),
           ("Passo 3", "Build: npm run build · Publish: build"),
           ("Passo 4", "Env: REACT_APP_BACKEND_URL"),
           ("Passo 5", "public/_redirects com /* /index.html 200"),
           ("Passo 6", "Atualize FRONTEND_URL na API")],
          code_block="/*    /index.html   200",
          links=[("Netlify", "https://www.netlify.com")]),

        P("Cloudflare", "Alternativa · Cloudflare Pages",
          "CDN forte, build similar ao da Vercel.",
          "Publicar painel com boa performance global.",
          "Root frontend + variável REACT_APP_BACKEND_URL + SPA fallback.",
          "Fallback errado = rotas quebradas.",
          [("Passo 1", "Workers & Pages → Create → Pages."),
           ("Passo 2", "Conecte o GitHub."),
           ("Passo 3", "Root: VBSOLUTIONCRMCodigoFonte-main/frontend"),
           ("Passo 4", "Build npm run build · Output build"),
           ("Passo 5", "Variable REACT_APP_BACKEND_URL + Node 20"),
           ("Passo 6", "Configure SPA e FRONTEND_URL na API")],
          links=[("Cloudflare Pages", "https://pages.cloudflare.com")]),

        P("Nginx FE", "Alternativa · Nginx na VPS servindo o build",
          "Útil se quiser painel e API no mesmo servidor.",
          "Servir arquivos estáticos com try_files SPA.",
          "npm run build local/CI → copia para root do Nginx.",
          "Sem try_files = 404 em rota profunda.",
          [("Passo 1", "No PC: npm run build com REACT_APP_BACKEND_URL da API."),
           ("Passo 2", "Envie a pasta build para a VPS."),
           ("Passo 3", "Aponte root do server Nginx para essa pasta."),
           ("Passo 4", "try_files $uri /index.html;"),
           ("Passo 5", "Certbot no domínio do painel."),
           ("Passo 6", "FRONTEND_URL = https do painel · restart API")],
          code_block="server {\n  listen 80;\n  server_name crm.suaempresa.com;\n  root /var/www/.../frontend/build;\n  index index.html;\n  location / { try_files $uri /index.html; }\n}"),

        P("Estático", "Qualquer host estático",
          "Hostgator compartilhada, S3+CloudFront, etc.: sobe o conteúdo de build.",
          "Flexibilidade quando Vercel não for opção.",
          "Upload dos arquivos + regra 404→index.html.",
          "Subir a pasta build inteira errada (com o wrapper) quebra paths.",
          [("Passo 1", "Gere build local com a URL da API."),
           ("Passo 2", "Envie o conteúdo interno de build/."),
           ("Passo 3", "Configure fallback SPA."),
           ("Passo 4", "Force HTTPS."),
           ("Passo 5", "Atualize FRONTEND_URL."),
           ("Passo 6", "Teste F5 em rota interna.")],
          note="<strong>Como funciona</strong><br/>Depois do build não existe mais Node no painel. Só arquivos."),

        P("Erros", "Erros comuns do frontend em produção",
          "Tabela para não chutar.",
          "Triagem rápida.",
          "Case sintoma → causa → ação.",
          "Ação errada (apagar projeto) perde domínio.",
          [("Passo 1", "Reproduza o erro e abra F12."),
           ("Passo 2", "Case na tabela."),
           ("Passo 3", "Mude só aquilo."),
           ("Passo 4", "Redeploy se for REACT_APP."),
           ("Passo 5", "Reteste login."),
           ("Passo 6", "Documente a correção.")],
          tbl=(["Sintoma", "Causa", "Ação"],
               [["Network localhost", "build antigo/env", "Variable + Redeploy"],
                ["CORS", "FRONTEND_URL", "URL idêntica + restart API"],
                ["404 no F5", "rewrite", "vercel.json / redirects"],
                ["Cannot find package.json", "Root", "apontar frontend"],
                ["Build eslint", "CI", "CI=false"]])),

        P("Segurança FE", "Segurança do painel",
          "Front não guarda segredo de banco. Mesmo assim há higiene.",
          "Reduzir vazamento e phishing de login.",
          "HTTPS, cookies/token no fluxo da API, não expor source map.",
          "GENERATE_SOURCEMAP=true facilita engenharia reversa.",
          [("Passo 1", "GENERATE_SOURCEMAP=false"),
           ("Passo 2", "HTTPS sempre no domínio."),
           ("Passo 3", "Não publique .env no repo."),
           ("Passo 4", "Admin com senha forte."),
           ("Passo 5", "Revise Variables periodicamente."),
           ("Passo 6", "Logout em computadores compartilhados.")],
          checks=["Sem sourcemap", "HTTPS", ".env fora do Git"]),

        P("Prompt 1", "Prompt Claude Code · configurar Vercel",
          "Use no VS Code com o repo aberto.",
          "Acelerar checklist sem inventar pastas.",
          "Assistente lista settings; você clica no painel Vercel.",
          "Prompt vago gera Root Directory inventado.",
          [("Passo 1", "Abra o terminal na raiz do download."),
           ("Passo 2", "Cole o prompt da bolha."),
           ("Passo 3", "Revise Root e env sugeridos."),
           ("Passo 4", "Aplique na Vercel."),
           ("Passo 5", "Deploy e valide Network."),
           ("Passo 6", "Guarde a URL no cofre do cliente.")],
          extra='<div class="script-bubble"><span class="label">Prompt</span>Configure o projeto Vercel para Root Directory VBSOLUTIONCRMCodigoFonte-main/frontend, CRA, Node 20, variáveis REACT_APP_BACKEND_URL (vou informar), DISABLE_ESLINT_PLUGIN=true, CI=false, GENERATE_SOURCEMAP=false, e confirme vercel.json com rewrite SPA. Não sugira hospedar o backend na Vercel.</div>'),

        P("Prompt 2", "Prompt Claude Code · CORS e quatro URLs",
          "Quando o login falha com CORS, este prompt encurta.",
          "Alinhar mundos front/API.",
          "Assistente compara URLs que você cola.",
          "Sem colar URL real o diagnóstico fica genérico.",
          [("Passo 1", "Copie URL do painel, URL da API e FRONTEND_URL atual."),
           ("Passo 2", "Cole o prompt com esses valores."),
           ("Passo 3", "Aplique as correções."),
           ("Passo 4", "Redeploy necessários."),
           ("Passo 5", "Reteste F12."),
           ("Passo 6", "Marque o checklist.")],
          extra='<div class="script-bubble"><span class="label">Prompt</span>Painel=[URL] API=[URL] FRONTEND_URL=[valor]. Monte a tabela das 4 variáveis (REACT_APP_BACKEND_URL, BACKEND_URL, PUBLIC_BACKEND_URL, FRONTEND_URL) sem barra final e diga exatamente o que mudar na Vercel e na API para acabar o CORS.</div>'),

        P("Passo a passo", "Do zero ao login · roteiro contínuo",
          "Uma página que amarra o fluxo inteiro sem pular PDF.",
          "Executar em sequência no dia do deploy.",
          "Conta → Root → Env → Deploy → CORS → teste.",
          "Pular CORS vira “deploy ok, login morto”.",
          [("Passo 1", "API HTTPS no ar (PDF VPS/Railway)."),
           ("Passo 2", "Conta Vercel + import repo."),
           ("Passo 3", "Root frontend + Node 20."),
           ("Passo 4", "Variables do pacote."),
           ("Passo 5", "Deploy + anotar URL."),
           ("Passo 6", "FRONTEND_URL na API + login F12.")],
          checks=["Roteiro completo", "Cliente consegue logar"]),

        P("Checklist", "Checklist publicação do painel",
          "Porteiro do “pode mandar o link”.",
          "Não anunciar URL pela metade.",
          "Itens binários ok/não.",
          "Item aberto = risco de suporte no mesmo dia.",
          [("Passo 1", "Leia a lista em voz alta."),
           ("Passo 2", "Marque só o que está feito de verdade."),
           ("Passo 3", "Transforme não em tarefa."),
           ("Passo 4", "Reteste login."),
           ("Passo 5", "Envie o link por canal seguro."),
           ("Passo 6", "Guarde print do checklist.")],
          checks=["Root frontend", "Node 20", "REACT_APP_BACKEND_URL HTTPS", "CI=false",
                  "vercel.json", "Deploy Ready", "CORS ok", "F5 em rota ok", "Sem segredo na Vercel"]),

        P("FAQ", "FAQ frontend e Vercel",
          "Dúvidas curtas do dia a dia.",
          "Destravar sem reabrir tudo.",
          "Pergunta → resposta.",
          "FAQ não substitui Network F12.",
          [("Passo 1", "Ache sua dúvida abaixo."),
           ("Passo 2", "Aplique a resposta."),
           ("Passo 3", "Se não couber, volte à tabela de erros."),
           ("Passo 4", "Documente o caso novo."),
           ("Passo 5", "Atualize FRONTEND_URL se mudou URL."),
           ("Passo 6", "Siga ao go-live.")],
          extra="""
          <div class="qa"><div class="q">Posso só arrastar a pasta build?</div><div class="a">Sim em host estático. Na Vercel o fluxo Git é melhor para update.</div></div>
          <div class="qa"><div class="q">Preview precisa de CORS?</div><div class="a">Sim. FRONTEND_URL deve incluir a origem que o Chrome usa, ou use API de homolog.</div></div>
          <div class="qa"><div class="q">Mudança de texto na tela?</div><div class="a">Commit + deploy. Não edite JS minificado na mão.</div></div>
          <div class="qa"><div class="q">API e front no mesmo domínio?</div><div class="a">Dá com proxy, mas este manual separa Vercel + API para WhatsApp estável.</div></div>
          """),

        P("Go-live", "Go-live do painel com a API",
          "Dia D: link no ar, time logando, API respondendo.",
          "Entrar em operação.",
          "Checklist front + API + um usuário real.",
          "Anunciar sem teste = primeiro ticket é o seu telefone.",
          [("Passo 1", "Checklist desta página e do PDF da API."),
           ("Passo 2", "Login com usuário do cliente."),
           ("Passo 3", "Abrir um ticket/menu crítico."),
           ("Passo 4", "Confirmar Network na API certa."),
           ("Passo 5", "Enviar URL e credenciais por canal seguro."),
           ("Passo 6", "Agendar o PDF WhatsApp se o canal ainda não estiver vivo.")],
          note="<strong>Recado</strong><br/>Desligar a API derruba o painel funcional mesmo com a Vercel no ar."),

        P("Monitor", "Depois do ar · o que olhar toda semana",
          "Deploy não é fim. É começo da operação.",
          "Pegar drift de Variable e domínio expirando.",
          "Olhar Deployments, Domains e um login teste.",
          "Ignorar até quebrar custa mais caro.",
          [("Passo 1", "Uma vez por semana: login teste."),
           ("Passo 2", "Confira Domains Valid."),
           ("Passo 3", "Veja se alguém mudou Variable sem Redeploy."),
           ("Passo 4", "Confira se a API ainda é a mesma URL."),
           ("Passo 5", "Revise usuários admin."),
           ("Passo 6", "Anote no runbook.")],
          checks=["Login semanal ok", "Domínio ok"]),

        P("Rollback", "Rollback na Vercel · voltar deploy anterior",
          "Se um deploy quebrou a tela, volte o anterior.",
          "Restaurar painel rápido.",
          "Deployments → Promote / Redeploy do build bom.",
          "Rollback do front não desfaz migrate do banco.",
          [("Passo 1", "Identifique o último Ready bom."),
           ("Passo 2", "Promote to Production ou Redeploy dele."),
           ("Passo 3", "Hard refresh."),
           ("Passo 4", "Confirme login."),
           ("Passo 5", "Corrija a branch com calma."),
           ("Passo 6", "Se o bug era Variable, corrija Variable e redeploy consciente.")],
          note="<strong>Onde acarreta</strong><br/>Rollback de front com API incompatível ainda falha: alinhe versões.", note_kind="warn"),

        P("CI", "Por que CI=false e DISABLE_ESLINT_PLUGIN",
          "CRA em CI trata warning como erro. Eslint no build pode matar deploy.",
          "Priorizar ir ao ar com código já validado no PC.",
          "Flags relaxam o pipeline da Vercel.",
          "Sem flags, deploy fica vermelho por warning cosmético.",
          [("Passo 1", "Adicione CI=false"),
           ("Passo 2", "Adicione DISABLE_ESLINT_PLUGIN=true"),
           ("Passo 3", "Redeploy"),
           ("Passo 4", "Continue lintando no PC (npm run lint se existir)"),
           ("Passo 5", "Não use isso como desculpa para ignore eterno de bug real"),
           ("Passo 6", "Se o time quiser CI rígido depois, prepare o código antes")],
          note="<strong>Como funciona</strong><br/>CI=true é padrão em muitos ambientes de nuvem. Aqui false evita falso negativo."),

        P("Prints", "O que pedir em print quando der erro",
          "Suporte bom nasce de evidência, não de “não abre”.",
          "Acelerar diagnóstico.",
          "URL, Network, Console, Variable names sem segredo.",
          "Print sem URL perde contexto de CORS.",
          [("Passo 1", "Print da URL completa do Chrome."),
           ("Passo 2", "Print do Console com o erro."),
           ("Passo 3", "Print do Network com a request falha."),
           ("Passo 4", "Lista de nomes de Variables (sem valores secretos)."),
           ("Passo 5", "Horário aproximado do erro."),
           ("Passo 6", "Se API, anexe 20 linhas de log.")],
          checks=["Kit de print montado"]),

        P("Cliente", "Como entregar o painel ao cliente",
          "Pacote mínimo para o cliente não ficar dependente de você a cada clique.",
          "Handoff claro.",
          "URL, usuários, aviso sobre API e .env.",
          "Entregar só o link sem aviso da API = surpresa quando alguém “desliga o servidor”.",
          [("Passo 1", "Envie URL do painel."),
           ("Passo 2", "Envie login admin por canal seguro."),
           ("Passo 3", "Explique: painel na Vercel, API em X, banco em Y."),
           ("Passo 4", "Avise que .env não está no GitHub."),
           ("Passo 5", "Passe o PDF WhatsApp se for o próximo passo."),
           ("Passo 6", "Combine canal de suporte e horário.")],
          note="<strong>Recado</strong><br/>Cliente feliz é cliente que sabe o que não pode desligar."),

        P("Fim", "Encerramento · links e próximo PDF",
          "Painel no ar. Próximo: banco bem documentado (Supabase) e canal WhatsApp.",
          "Fechar o módulo frontend.",
          "Ordem sugerida de leitura/execução.",
          "Pular WhatsApp com painel ok ainda deixa operação muda.",
          [("Passo 1", "Marque o checklist de publicação."),
           ("Passo 2", "Confirme as 4 URLs."),
           ("Passo 3", "Abra o PDF Supabase se o banco ainda não estiver redondo."),
           ("Passo 4", "Abra o PDF WhatsApp para Redis e canal."),
           ("Passo 5", "Guarde URLs no cofre."),
           ("Passo 6", "Arquive prints do go-live.")],
          links=[("Vercel", "https://vercel.com"), ("Repo", "https://github.com/visaobusinesstech/codigo-fonte-COUTINHO"),
                 ("Node", "https://nodejs.org")],
          note="<strong>Visão Business · VB Solution CRM</strong><br/>Treinamento · Hospedagem Frontend Vercel · 50 páginas · © Visão Business"),
    ]
    # expand to 49 with practical fillers if needed
    fillers = [
        P("Cache", "Cache do Chrome e hard refresh",
          "Às vezes o deploy novo existe e o Chrome mostra o JS velho.",
          "Ver a versão nova de verdade.",
          "Ctrl+F5 ou limpar cache do site.",
          "Diagnóstico errado de “variable não pegou”.",
          [("Passo 1", "Ctrl+F5 após cada redeploy."),
           ("Passo 2", "Se possível, janela anônima."),
           ("Passo 3", "Confira Network → Disable cache com F12 aberto."),
           ("Passo 4", "Compare hash dos arquivos estáticos."),
           ("Passo 5", "Só então mexa de novo em Variable."),
           ("Passo 6", "Documente se o time usa proxy corporativo com cache.")]),
        P("Branches", "Branch main e deploys acidentais",
          "Push em main pode publicar Production sem querer.",
          "Controlar o que vai ao cliente.",
          "Production Branch nas settings.",
          "Feature crua no ar = vergonha pública.",
          [("Passo 1", "Settings → Git → Production Branch = main (ou a combinada)."),
           ("Passo 2", "Trabalhe features em branch."),
           ("Passo 3", "Use Preview para teste."),
           ("Passo 4", "Merge só após checklist."),
           ("Passo 5", "Avise o time do fluxo."),
           ("Passo 6", "Proteja main no GitHub se possível.")]),
        P("Env Preview", "Separar Variable de Preview",
          "Preview pode apontar para API de homolog.",
          "Não misturar dado real em teste.",
          "Variables por Environment na Vercel.",
          "Preview em produção sem querer suja dado.",
          [("Passo 1", "Crie API homolog."),
           ("Passo 2", "REACT_APP_BACKEND_URL de Preview = API homolog."),
           ("Passo 3", "Production aponta para API real."),
           ("Passo 4", "FRONTEND_URL correspondente em cada API."),
           ("Passo 5", "Teste preview com usuário fake."),
           ("Passo 6", "Nunca use número WhatsApp real no preview.")]),
        P("Auditoria", "Auditoria rápida de 10 minutos",
          "Rotina curta para manager não técnico.",
          "Pegar drift.",
          "Lista fixa de cliques.",
          "Sem rotina o sistema apodrece em silêncio.",
          [("Passo 1", "Abrir painel e logar."),
           ("Passo 2", "Abrir Deployments: último Ready quando?"),
           ("Passo 3", "Domains: status Valid?"),
           ("Passo 4", "Variables: nomes esperados existem?"),
           ("Passo 5", "F12 Network: host da API."),
           ("Passo 6", "Anotar no runbook.")]),
        P("Integração", "Encaixe com o PDF da API",
          "Os dois manuais se encontram nas URLs.",
          "Operar como um sistema só.",
          "Front publica origem; API libera CORS e atende REST.",
          "Time que lê só um PDF deixa buraco.",
          [("Passo 1", "Tenha o PDF VPS/Railway ao lado."),
           ("Passo 2", "Copie BACKEND_URL de lá."),
           ("Passo 3", "Cole em REACT_APP_BACKEND_URL."),
           ("Passo 4", "Devolva a URL Vercel para FRONTEND_URL."),
           ("Passo 5", "Redeploy dos dois lados se precisar."),
           ("Passo 6", "Teste ponta a ponta.")]),
        P("Performance", "Build menor e sourcemap",
          "GENERATE_SOURCEMAP=false reduz artefato.",
          "Deploy mais leve e menos exposição.",
          "CRA deixa de emitir .map.",
          "Sourcemap em produção ajuda atacante a ler seu código.",
          [("Passo 1", "Variable GENERATE_SOURCEMAP=false"),
           ("Passo 2", "Redeploy"),
           ("Passo 3", "Confirme ausência de .map grandes"),
           ("Passo 4", "Mantenha sourcemap só em ambiente interno se precisar"),
           ("Passo 5", "Monitore tempo de build"),
           ("Passo 6", "Se build lento, revise dependências com o time dev")]),
        P("Acessos", "Quem pode deployar",
          "Poucas pessoas com acesso de produção.",
          "Evitar deploy acidental.",
          "Time Vercel + proteção de branch.",
          "Estagiário com acesso Production vira risco.",
          [("Passo 1", "Liste quem tem acesso ao projeto Vercel."),
           ("Passo 2", "Remova contas antigas."),
           ("Passo 3", "Use SSO/GitHub org se houver."),
           ("Passo 4", "Combine que só lead promove Production."),
           ("Passo 5", "Registre no runbook."),
           ("Passo 6", "Revise a cada trimestre.")]),
        P("HTTP", "Nunca publicar o painel em HTTP puro",
          "Login e token em HTTP são abdução fácil.",
          "Proteger credencial em trânsito.",
          "Vercel já entrega HTTPS; domínio próprio precisa SSL ok.",
          "Aviso de site inseguro derruba confiança do cliente.",
          [("Passo 1", "Confira cadeado na URL."),
           ("Passo 2", "Force HTTPS no domínio."),
           ("Passo 3", "API também HTTPS."),
           ("Passo 4", "Evite mixed content (http dentro de https)."),
           ("Passo 5", "Reteste login."),
           ("Passo 6", "Eduque o time a não aceitar “avançar mesmo assim”.")],
          note_kind="danger",
          note="<strong>Segurança</strong><br/>HTTP em produção é inaceitável para CRM com dados de cliente."),
        P("Suporte", "Roteiro de suporte nível 1",
          "Para quem atende o telefone do cliente.",
          "Triagem sem acesso root.",
          "Perguntas fixas.",
          "Escalar cedo com print certo.",
          [("Passo 1", "Qual URL exatamente?"),
           ("Passo 2", "Consegue ver a tela de login?"),
           ("Passo 3", "Erro no Chrome? Peça print."),
           ("Passo 4", "Começou depois de algum deploy?"),
           ("Passo 5", "Outro usuário/rede funciona?"),
           ("Passo 6", "Escale com kit de print se for CORS/API.")]),
        P("Encerramento prático", "Simulado final de 20 minutos",
          "Treino antes do go-live real.",
          "Provar que o time executa sem você.",
          "Cronômetro + checklist.",
          "Descobrir buraco com calma.",
          [("Passo 1", "Apague Variable de propósito em preview e corrija."),
           ("Passo 2", "Faça Redeploy consciente."),
           ("Passo 3", "Quebre FRONTEND_URL em homolog e corrija CORS."),
           ("Passo 4", "Teste F5 em rota."),
           ("Passo 5", "Faça rollback de um deploy preview."),
           ("Passo 6", "Registre o tempo e as falhas humanas.")]),
    ]
    pages = ensure_count(M, pages, fillers)
    write_doc(
        "02-hospedagem-frontend-vercel.html",
        "Treinamento · Hospedagem Frontend Vercel · VB Solution CRM",
        cover(
            "SÉRIE CÓDIGO-FONTE · FRONTEND · 50 PÁGINAS",
            "Hospedagem do Frontend · Vercel e alternativas",
            "Manual passo a passo para publicar o painel React do VB Solution CRM na Vercel (e alternativas), com variáveis, CORS, domínio, checklist e prompts para Claude Code. Linguagem direta, para leigo acompanhar e executar.",
            [("Público", "Compradores do código-fonte"), ("Foco", "Painel React"), ("Plataforma", "Vercel (+ Netlify/CF/Nginx)"), ("Formato", "50 páginas densas")],
        ),
        pack(M, pages),
    )


if __name__ == "__main__":
    # styles
    import page_factory  # noqa: F401
    print("TOTAL", TOTAL)
    doc_vercel()
    print("02 ok")
