/**
 * Copyright (c) Visão Business. Todos os direitos reservados.
 * VB Solution CRM — propriedade intelectual da Visão Business.
 * Uso conforme LICENSE na raiz do repositório.
 */

import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import dashboardRoutes from "./dashboardRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import chatRoutes from "./chatRoutes";
import queueIntegrationRoutes from "./queueIntegrationRoutes";
import chatBotRoutes from "./chatBotRoutes";
import webHookRoutes from "./webHookRoutes";
import subScriptionRoutes from "./subScriptionRoutes";
import invoiceRoutes from "./invoicesRoutes";
import apiRoutes from "./apiRoutes";
import versionRouter from "./versionRoutes";
import filesRoutes from "./filesRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import apiCompanyRoutes from "./api/apiCompanyRoutes";
import apiContactRoutes from "./api/apiContactRoutes";
import apiMessageRoutes from "./api/apiMessageRoutes";
import companySettingsRoutes from "./companySettingsRoutes";
import ticketFinalizationReasonRoutes from "./ticketFinalizationReasonRoutes";
import presetWebhookRoutes from "./presetWebhookRoutes";
import birthdayRoutes from "./birthdayRoutes";
import promptRoutes from "./promptRouter";
import statisticsRoutes from "./statisticsRoutes";
import scheduleMessageRoutes from "./ScheduledMessagesRoutes";
import flowDefaultRoutes from "./flowDefaultRoutes";
import webHook from "./webHookRoutes";
import flowBuilder from "./flowBuilderRoutes";
import flowCampaignRoutes from "./flowCampaignRoutes";
import callRoutes from "./callRoutes";
import companyKanbanRoutes from "./companyKanbanRoutes";
import metaRoutes from "./metaRoutes";
import smsRoutes, { smsWebhookRoutes } from "./smsRoutes";
import telegramRoutes, { telegramWebhookRoutes } from "./telegramRoutes";
import telegramUserRoutes from "./telegramUserRoutes";
import linkedinRoutes, { linkedinWebhookRoutes } from "./linkedinRoutes";
import { googleOAuthCallbackRoutes } from "./googleOAuthLoginRoutes";
import agentProactiveRoutes from "./agentProactiveRoutes";
import activityRoutes from "./activityRoutes";
import projectRoutes from "./projectRoutes";
import convertedLeadRoutes from "./convertedLeadRoutes";
import leadsSalesRoutes from "./leadsSalesRoutes";
import emailTemplateRoutes from "./emailTemplateRoutes";
import emailContactRoutes from "./emailContactRoutes";
import emailRoutes from "./emailRoutes";
import smtpRoutes from "./smtpRoutes";
import emailCampaignRoutes from "./emailCampaignRoutes";
import emailScheduleRoutes from "./emailScheduleRoutes";
import inventoryRoutes from "./inventoryRoutes";
import realtyCrmRoutes from "./realtyCrmRoutes";
import leadPipelineRoutes from "./leadPipelineRoutes";
import activityStageRoutes from "./activityStageRoutes";
import paymentsWebhookRoutes from "./paymentsWebhookRoutes";
import stripeBillingRoutes from "./stripeBillingRoutes";
import aiBrainRoutes from "./aiBrainRoutes";
import anthropicRoutes from "../providers/anthropic/routes/anthropicRoutes";
import geminiRoutes from "../providers/gemini/routes/geminiRoutes";
import grokRoutes from "../providers/grok/routes/grokRoutes";
import figmaIntegrationRoutes from "./figmaIntegrationRoutes";
import githubIntegrationRoutes from "./githubIntegrationRoutes";
import brainGithubRoutes, {
  githubOAuthCallbackRoutes
} from "./brainGithubRoutes";
import apiCredentialRoutes from "./apiCredentialRoutes";
import crmApiV1Routes from "./crmApiV1Routes";

import ChatController from "../controllers/ChatController";

const routes = Router();

routes.use("/v1", metaRoutes);
routes.use("/v1", smsWebhookRoutes);
routes.use("/v1", telegramWebhookRoutes);
routes.use("/v1", linkedinWebhookRoutes);
routes.use(googleOAuthCallbackRoutes);
routes.use(githubOAuthCallbackRoutes);
routes.use(smsRoutes);
routes.use(telegramRoutes);
routes.use(telegramUserRoutes);
routes.use(linkedinRoutes);
routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use("/api/messages", apiRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(companyRoutes);
routes.use(planRoutes);
routes.use(ticketNoteRoutes);
routes.use(quickMessageRoutes);
routes.use(helpRoutes);
routes.use(dashboardRoutes);
routes.use(birthdayRoutes);
routes.use(scheduleRoutes);
routes.use(tagRoutes);
routes.use(contactListRoutes);
routes.use(contactListItemRoutes);
routes.use(campaignRoutes);
routes.use(campaignSettingRoutes);
routes.use(announcementRoutes);
routes.use(chatRoutes);
routes.use(chatBotRoutes);
routes.use("/webhook", webHookRoutes);
routes.use(subScriptionRoutes);
routes.use(invoiceRoutes);
routes.use(versionRouter);
routes.use(filesRoutes);
routes.use(queueOptionRoutes);
routes.use(queueIntegrationRoutes);
routes.use(ticketTagRoutes);
routes.use("/api", apiCompanyRoutes);
routes.use("/api", apiContactRoutes);
routes.use("/api", apiMessageRoutes);
routes.use(presetWebhookRoutes);
routes.use(promptRoutes);
routes.use(statisticsRoutes);
routes.use(companySettingsRoutes);
routes.use(ticketFinalizationReasonRoutes);
routes.use(scheduleMessageRoutes);

routes.use(flowDefaultRoutes);
// Evita duplicar montagem do webhook na raiz; já existe em "/webhook"
routes.use(flowBuilder);
routes.use(flowCampaignRoutes);
routes.use("/call", callRoutes);
routes.use(companyKanbanRoutes);
routes.use(agentProactiveRoutes);
routes.use(activityRoutes);
routes.use(projectRoutes);
routes.use(convertedLeadRoutes);
routes.use(leadsSalesRoutes);
routes.use(emailTemplateRoutes);
routes.use(emailContactRoutes);
routes.use(emailRoutes);
routes.use(smtpRoutes);
routes.use(emailCampaignRoutes);
routes.use(emailScheduleRoutes);
routes.use(inventoryRoutes);
routes.use(realtyCrmRoutes);
routes.use(leadPipelineRoutes);
routes.use(activityStageRoutes);

routes.use(aiBrainRoutes);
routes.use(brainGithubRoutes);
routes.use(anthropicRoutes);
routes.use(geminiRoutes);
routes.use(grokRoutes);
routes.use(figmaIntegrationRoutes);
routes.use(githubIntegrationRoutes);
routes.use("/api/webhook/payments", paymentsWebhookRoutes);
routes.use(stripeBillingRoutes);
routes.use(apiCredentialRoutes);
routes.use("/api/v1/crm", crmApiV1Routes);

routes.post("/chats/backfill", ChatController.backfillChats);

export default routes;
