/**
 * Copyright (c) Visão Business. Todos os direitos reservados.
 * VB Solution CRM — propriedade intelectual da Visão Business.
 * Uso conforme LICENSE na raiz do repositório.
 *
 * Modelos prontos de fluxos de nutrição (camelCase alinhado ao backend).
 */

const wa = (ordem, diasApos, titulo, mensagem) => ({
  ordem,
  diasApos,
  canal: "whatsapp",
  titulo,
  mensagem,
  ativo: true,
});

const mail = (ordem, diasApos, titulo, mensagem) => ({
  ordem,
  diasApos,
  canal: "email",
  titulo,
  mensagem,
  ativo: true,
});

export const CATEGORIAS_MODELO = {
  reativacao: "Reativação de inativos",
  sem_resposta: "Leads sem resposta",
  valor: "Conteúdo de valor",
  relacionamento: "Relacionamento e pós-venda",
  segmentado: "Segmentados (etapa / perfil / perda)",
  jornada: "Jornada e ciclo de vida",
};

export const MODELOS_NUTRICAO = [
  {
    id: "reativacao-30",
    categoria: "reativacao",
    resumo: "3 toques leves para quem sumiu há 30 dias, com oferta de novidades e saída educada.",
    fluxo: {
      nome: "Reativação 30 dias — retomada leve",
      descricao: "Sequência curta para leads sem interação há 30 dias.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 30,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
    },
    etapas: [
      wa(1, 0, "Retomada leve", "Oi {{primeiro_nome}}, tudo bem? Passando para saber se a sua busca por imóvel continua ativa. Se quiser, te mando as opções mais recentes que entraram na nossa carteira."),
      wa(2, 4, "Novidades da carteira", "{{primeiro_nome}}, entraram imóveis novos que combinam com o que você procurava. Quer que eu envie 3 opções selecionadas?"),
      wa(3, 8, "Encerramento educado", "{{primeiro_nome}}, vou pausar os envios por aqui para não te incomodar. Quando quiser retomar a busca, é só me chamar — guardo o seu perfil."),
    ],
  },
  {
    id: "reativacao-60",
    categoria: "reativacao",
    resumo: "Reengajamento de 60 dias com atualização de mercado e revisão do perfil de busca.",
    fluxo: {
      nome: "Reativação 60 dias — atualizar perfil",
      descricao: "Para leads frios: atualiza critérios de busca e reapresenta o mercado.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 60,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Mudou algo na busca?", "Oi {{primeiro_nome}}! Faz um tempo que não conversamos. Seus critérios mudaram (bairro, valor, número de quartos)? Atualizo aqui e te mando só o que faz sentido."),
      mail(2, 5, "Panorama do mercado", "Olá {{nome}},\n\nSeparei um resumo rápido do que mudou no mercado da sua região: preço médio, tempo de venda e bairros em alta.\n\nQuer receber a lista de imóveis que se encaixam no seu perfil?"),
      wa(3, 12, "Última chamada", "{{primeiro_nome}}, se ainda faz sentido buscar imóvel neste semestre, me avisa que retomo a curadoria para você."),
    ],
  },
  {
    id: "reativacao-90",
    categoria: "reativacao",
    resumo: "Resgate de leads muito antigos (90 dias) com condição especial e prova social.",
    fluxo: {
      nome: "Resgate 90 dias — oportunidade",
      descricao: "Último ciclo de resgate para leads antigos, com prova social e oferta.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 90,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Oportunidade do mês", "Oi {{primeiro_nome}}, temos oportunidades abaixo do valor de mercado nesta semana. Posso te enviar as 3 melhores?"),
      wa(2, 6, "Prova social", "{{primeiro_nome}}, ajudamos clientes com um perfil parecido com o seu a fechar recentemente. Quer ver o que conseguimos negociar?"),
      mail(3, 14, "Fico à disposição", "Olá {{nome}},\n\nVou encerrar os envios automáticos por aqui. Se em algum momento voltar a considerar comprar ou alugar, respondo este e-mail e retomamos do ponto em que paramos."),
    ],
  },
  {
    id: "sem-resposta-7",
    categoria: "sem_resposta",
    resumo: "Follow-up rápido em 7 dias para quem não respondeu ao primeiro contato.",
    fluxo: {
      nome: "Sem resposta — 3 tentativas em 10 dias",
      descricao: "Cadência curta para leads que não responderam ao contato inicial.",
      publicoAlvo: "lead_sem_resposta",
      diasInatividade: 7,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
    },
    etapas: [
      wa(1, 0, "Confirmação de canal", "Oi {{primeiro_nome}}, tentei falar com você sobre o imóvel de interesse. Prefere que eu te chame por WhatsApp, ligação ou e-mail?"),
      wa(2, 3, "Facilita a resposta", "{{primeiro_nome}}, para agilizar: responde só com 1 (quero ver opções), 2 (quero visitar) ou 3 (agora não é o momento)."),
      wa(3, 7, "Encerramento", "Sem problemas, {{primeiro_nome}}! Encerro por aqui e deixo seu contato salvo. Quando quiser retomar, é só chamar."),
    ],
  },
  {
    id: "sem-resposta-visita",
    categoria: "sem_resposta",
    resumo: "Recuperação de leads que pediram visita e não confirmaram.",
    fluxo: {
      nome: "Visita não confirmada — reagendamento",
      descricao: "Reengaja quem demonstrou interesse em visitar mas não confirmou.",
      publicoAlvo: "lead_sem_resposta",
      diasInatividade: 5,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Reagendar visita", "Oi {{primeiro_nome}}, consigo encaixar sua visita ainda esta semana. Prefere manhã ou fim da tarde?"),
      wa(2, 3, "Alternativas parecidas", "{{primeiro_nome}}, se aquele imóvel não te agradou, tenho 2 opções muito parecidas na mesma faixa de preço. Quer ver?"),
      wa(3, 7, "Encerrar com porta aberta", "{{primeiro_nome}}, deixo a agenda aberta. Quando quiser marcar, me manda um oi."),
    ],
  },
  {
    id: "conteudo-comprador",
    categoria: "valor",
    resumo: "Educação do comprador: financiamento, documentação e custos de aquisição.",
    fluxo: {
      nome: "Conteúdo de valor — comprador",
      descricao: "Entrega informação útil enquanto o lead amadurece a decisão.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 20,
      canal: "email",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      mail(1, 0, "Quanto custa além do imóvel", "Olá {{nome}},\n\nMuita gente esquece dos custos de ITBI, registro e escritura. Fiz um resumo com os percentuais atualizados para você planejar melhor.\n\nQuer que eu simule com base no valor que você pretende investir?"),
      mail(2, 7, "Financiamento sem susto", "Olá {{nome}},\n\nComparei as condições dos principais bancos: taxa, prazo e entrada mínima. Posso fazer uma simulação com o seu perfil e enviar em seguida."),
      wa(3, 14, "Simulação personalizada", "{{primeiro_nome}}, quer que eu faça uma simulação de financiamento com o seu perfil? Levo cerca de 10 minutos e te mando por aqui."),
    ],
  },
  {
    id: "conteudo-investidor",
    categoria: "valor",
    resumo: "Nutrição de investidores com rentabilidade, valorização e imóveis de renda.",
    fluxo: {
      nome: "Conteúdo de valor — investidor",
      descricao: "Sequência focada em rentabilidade e valorização por região.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 30,
      canal: "email",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      mail(1, 0, "Onde o metro quadrado subiu", "Olá {{nome}},\n\nSeparei as regiões com maior valorização nos últimos 12 meses e o rendimento médio de aluguel em cada uma.\n\nQuer receber as oportunidades com melhor relação preço x renda?"),
      wa(2, 6, "Imóveis de renda", "{{primeiro_nome}}, tenho unidades já alugadas, com contrato ativo e rentabilidade acima da média. Te mando os números?"),
      mail(3, 15, "Carteira selecionada", "Olá {{nome}},\n\nMonto uma carteira de opções conforme o valor que pretende investir e o retorno desejado. Me responde com o ticket que trabalho a seleção."),
    ],
  },
  {
    id: "conteudo-locatario",
    categoria: "valor",
    resumo: "Apoio a quem busca locação: documentação, garantias e prazos.",
    fluxo: {
      nome: "Conteúdo de valor — locação",
      descricao: "Reduz atrito na locação explicando garantias e documentos.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 21,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Documentos e garantias", "Oi {{primeiro_nome}}! Para alugar rápido, vale saber quais garantias aceitamos (fiador, seguro-fiança ou caução). Quer que eu te explique a mais simples para o seu caso?"),
      wa(2, 5, "Opções disponíveis", "{{primeiro_nome}}, tenho unidades disponíveis para entrada imediata dentro do seu orçamento. Quer a lista atualizada?"),
      mail(3, 12, "Checklist do locatário", "Olá {{nome}},\n\nSegue o checklist com tudo que costuma ser pedido na análise cadastral. Com isso em mãos, a aprovação sai em poucos dias."),
    ],
  },
  {
    id: "pos-venda",
    categoria: "relacionamento",
    resumo: "Pós-venda em 30/90/180 dias para gerar indicação e recompra.",
    fluxo: {
      nome: "Pós-venda — indicação e recompra",
      descricao: "Mantém o relacionamento após o fechamento e pede indicações.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 30,
      canal: "whatsapp",
      encerrarAoResponder: false,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Como está a mudança?", "Oi {{primeiro_nome}}, tudo certo com o imóvel? Se precisar de indicação de reforma, mudança ou documentação, me chama."),
      wa(2, 60, "Pedido de indicação", "{{primeiro_nome}}, você conhece alguém procurando imóvel? Cuido dessa pessoa com o mesmo carinho que cuidei de você."),
      mail(3, 150, "Avaliação gratuita", "Olá {{nome}},\n\nJá se passaram alguns meses e o mercado mudou. Posso preparar uma avaliação gratuita atualizada do seu imóvel — é só responder este e-mail."),
    ],
  },
  {
    id: "proprietario-carteira",
    categoria: "relacionamento",
    resumo: "Relacionamento com proprietários: desempenho do anúncio e ajuste de preço.",
    fluxo: {
      nome: "Proprietário — desempenho do anúncio",
      descricao: "Atualiza o proprietário sobre visitas, propostas e preço praticado.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 15,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Resumo da semana", "Oi {{primeiro_nome}}, seguem os números do seu imóvel: visualizações, contatos e visitas agendadas. Quer que eu detalhe?"),
      wa(2, 10, "Ajuste de estratégia", "{{primeiro_nome}}, com base nos imóveis concorrentes, um pequeno ajuste de valor ou novas fotos podem acelerar bastante. Posso te mostrar a comparação?"),
      mail(3, 25, "Estudo de mercado", "Olá {{nome}},\n\nPreparo um estudo comparativo com os imóveis similares anunciados na região, com sugestão de preço e prazo estimado de venda."),
    ],
  },
  {
    id: "datas-especiais",
    categoria: "relacionamento",
    resumo: "Momentos-chave: aniversário do contrato, fim de ano e renovação de locação.",
    fluxo: {
      nome: "Momentos-chave — datas do cliente",
      descricao: "Toques pontuais em datas relevantes da jornada do cliente.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 45,
      canal: "whatsapp",
      encerrarAoResponder: false,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Aniversário do contrato", "Oi {{primeiro_nome}}! Seu contrato faz aniversário agora. Quer que eu revise as condições e veja se dá para melhorar algo?"),
      wa(2, 30, "Check-in de satisfação", "{{primeiro_nome}}, de 0 a 10, como você avalia nosso atendimento? Seu retorno ajuda demais a melhorar."),
      mail(3, 90, "Novidades e oportunidades", "Olá {{nome}},\n\nUm resumo do que aconteceu no mercado desde o nosso último contato, com as oportunidades que separei pensando no seu perfil."),
    ],
  },
  {
    id: "seg-proposta-parada",
    categoria: "segmentado",
    resumo: "Para quem travou na etapa Proposta: reforço de valor, flexibilização e último chamado.",
    fluxo: {
      nome: "Proposta parada — destravar negociação",
      descricao: "Leads que estacionaram na etapa Proposta do pipeline.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 7,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoEstagios: ["proposta"],
    },
    etapas: [
      wa(1, 0, "Status da proposta", "Oi {{primeiro_nome}}, sua proposta segue em pé aqui. Falta algum ponto para você decidir? Consigo negociar condições."),
      wa(2, 3, "Flexibilização", "{{primeiro_nome}}, conversei com o proprietário sobre prazo e forma de pagamento. Quer que eu leve uma contraproposta?"),
      wa(3, 7, "Último chamado", "{{primeiro_nome}}, preciso dar um retorno ao proprietário. Seguimos com a proposta ou prefere que eu busque outras opções?"),
    ],
  },
  {
    id: "seg-visita-sem-retorno",
    categoria: "segmentado",
    resumo: "Leads na etapa Visita que não deram retorno: feedback, alternativas e reagendamento.",
    fluxo: {
      nome: "Pós-visita sem retorno",
      descricao: "Leads parados na etapa Visita.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 5,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoEstagios: ["visita"],
    },
    etapas: [
      wa(1, 0, "Feedback da visita", "{{primeiro_nome}}, o que você achou do imóvel que visitamos? Seu feedback me ajuda a acertar as próximas opções."),
      wa(2, 4, "Alternativas parecidas", "Separei imóveis bem parecidos com o que visitamos, com ajustes no que não te agradou. Quer ver?"),
      wa(3, 9, "Reagendar", "{{primeiro_nome}}, consigo montar um roteiro com 2 ou 3 visitas no mesmo dia. Qual período fica melhor para você?"),
    ],
  },
  {
    id: "seg-investidor",
    categoria: "segmentado",
    resumo: "Perfil investidor: rentabilidade, oportunidades abaixo do mercado e análise de carteira.",
    fluxo: {
      nome: "Investidor — oportunidades e rentabilidade",
      descricao: "Conteúdo focado em retorno para leads com perfil investidor.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 20,
      canal: "whatsapp",
      encerrarAoResponder: false,
      ativo: true,
      segmentoPerfis: ["investidor"],
    },
    etapas: [
      wa(1, 0, "Rentabilidade da região", "{{primeiro_nome}}, fechei o cálculo de rentabilidade média de locação na região que você acompanha. Quer receber o resumo?"),
      wa(2, 10, "Oportunidade abaixo do mercado", "Entrou um imóvel com valor abaixo da média do prédio e boa liquidez. Te envio os números?"),
      mail(3, 25, "Análise de carteira", "Olá {{nome}},\n\nMonto uma análise simples de retorno (aluguel, valorização e custos) para os imóveis que você está avaliando."),
    ],
  },
  {
    id: "seg-locatario",
    categoria: "segmentado",
    resumo: "Perfil locatário: novas unidades, apoio na documentação e condições facilitadas.",
    fluxo: {
      nome: "Locatário — novas unidades e documentação",
      descricao: "Sequência para leads de locação.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 15,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoPerfis: ["locatario"],
    },
    etapas: [
      wa(1, 0, "Novas unidades para alugar", "{{primeiro_nome}}, entraram novas unidades para locação no seu perfil de busca. Quer que eu envie?"),
      wa(2, 6, "Apoio na documentação", "Se o que travou foi garantia ou documentação, temos opções (seguro-fiança, caução). Posso te explicar rapidinho?"),
      wa(3, 12, "Condições facilitadas", "{{primeiro_nome}}, alguns proprietários estão aceitando isenção do primeiro mês. Quer ver essas unidades?"),
    ],
  },
  {
    id: "seg-perda-preco",
    categoria: "segmentado",
    resumo: "Perdidos por preço: opções dentro do orçamento, quedas de valor e simulação.",
    fluxo: {
      nome: "Perdido por preço — resgate com orçamento certo",
      descricao: "Leads perdidos por preço acima do orçamento.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 30,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoMotivosPerda: ["Preço acima do orçamento"],
    },
    etapas: [
      wa(1, 0, "Dentro do seu orçamento", "Oi {{primeiro_nome}}, lembrei de você: entraram imóveis dentro da faixa de valor que fazia sentido para você. Quer ver?"),
      wa(2, 12, "Queda de preço", "{{primeiro_nome}}, dois imóveis que você gostou tiveram redução de valor. Te envio a lista atualizada?"),
      mail(3, 30, "Simulação de parcelas", "Olá {{nome}},\n\nPosso montar uma simulação de financiamento com entrada e parcelas dentro do seu orçamento. Quer que eu prepare?"),
    ],
  },
  {
    id: "seg-perda-concorrencia",
    categoria: "segmentado",
    resumo: "Perdidos para a concorrência: relacionamento de longo prazo e indicação.",
    fluxo: {
      nome: "Perdido para concorrência — relacionamento futuro",
      descricao: "Leads que fecharam com outra imobiliária.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 45,
      canal: "whatsapp",
      encerrarAoResponder: false,
      ativo: false,
      segmentoMotivosPerda: ["Comprou/alugou com outra imobiliária"],
    },
    etapas: [
      wa(1, 0, "Parabéns pela conquista", "{{primeiro_nome}}, fiquei sabendo que você fechou negócio — parabéns! Fico à disposição para o que precisar do imóvel."),
      wa(2, 60, "Indicação", "{{primeiro_nome}}, se algum amigo ou familiar estiver procurando imóvel, posso ajudar com todo o cuidado que você conhece."),
      mail(3, 150, "Gestão e valorização", "Olá {{nome}},\n\nSe um dia quiser avaliar, alugar ou vender esse imóvel, faço um estudo de valorização sem compromisso."),
    ],
  },
  {
    id: "jornada-boas-vindas",
    categoria: "jornada",
    resumo: "Nascimento do lead: boas-vindas imediatas, expectativa de atendimento e qualificação do perfil.",
    fluxo: {
      nome: "Nascimento do lead — boas-vindas e qualificação",
      descricao: "Primeiros toques logo após a entrada do lead no CRM.",
      publicoAlvo: "lead_sem_resposta",
      diasInatividade: 1,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoEstagios: ["novos"],
    },
    etapas: [
      wa(1, 0, "Boas-vindas", "Oi {{primeiro_nome}}, aqui é da nossa equipe! Recebi seu contato e já estou cuidando da sua busca. Pode me dizer a região e a faixa de valor que você tem em mente?"),
      wa(2, 1, "Qualificação do perfil", "{{primeiro_nome}}, para eu enviar só o que faz sentido: é para morar ou investir? Quantos quartos e vaga você precisa?"),
      mail(3, 3, "Como vamos te ajudar", "Olá {{nome}},\n\nObrigado pelo contato. A partir de agora você recebe uma curadoria de imóveis alinhada ao seu perfil, sem excesso de mensagens.\n\nSe preferir falar por telefone, é só responder este e-mail com o melhor horário."),
      wa(4, 6, "Curadoria inicial", "{{primeiro_nome}}, montei uma primeira seleção com base no que você me passou. Quer que eu envie agora?"),
    ],
  },
  {
    id: "jornada-troca-status",
    categoria: "jornada",
    resumo: "Troca de status: lead virou qualificado e precisa de próximo passo claro (visita ou proposta).",
    fluxo: {
      nome: "Troca de status — qualificado sem próximo passo",
      descricao: "Leads que avançaram para qualificados mas não agendaram nada.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 3,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoEstagios: ["qualificados", "mandar_opcoes"],
    },
    etapas: [
      wa(1, 0, "Próximo passo", "{{primeiro_nome}}, já entendi bem o que você procura. O próximo passo é ver de perto: prefere visitar durante a semana ou no sábado?"),
      wa(2, 3, "Roteiro de visitas", "Consigo agrupar 2 ou 3 imóveis no mesmo roteiro para você não perder tempo. Qual período fica melhor?"),
      wa(3, 7, "Tirar dúvidas antes de decidir", "{{primeiro_nome}}, ficou alguma dúvida sobre documentação, condomínio ou financiamento? Posso resolver isso antes da visita."),
    ],
  },
  {
    id: "jornada-preco-ideal",
    categoria: "jornada",
    resumo: "\"Chegou o preço ideal\": avisa quando entra imóvel na faixa do cliente ou cai o valor de um favorito.",
    fluxo: {
      nome: "Chegou o preço ideal — alerta de oportunidade",
      descricao: "Aviso quando surge imóvel dentro do orçamento ou com redução de preço.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 20,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
    },
    etapas: [
      wa(1, 0, "Entrou na sua faixa", "{{primeiro_nome}}, boa notícia: entrou um imóvel dentro da faixa de valor que você queria, no perfil que buscamos. Te envio as fotos?"),
      wa(2, 5, "Queda de preço", "{{primeiro_nome}}, um imóvel que combina com o seu perfil baixou de preço agora. Quer ver os números antes de virar concorrência?"),
      mail(3, 12, "Comparativo de valores", "Olá {{nome}},\n\nSegue um comparativo rápido entre os imóveis disponíveis hoje na sua faixa de preço, com valor por m2 e potencial de negociação.\n\nPosso agendar uma visita no que mais te interessar."),
      wa(4, 20, "Janela de negociação", "{{primeiro_nome}}, o proprietário sinalizou abertura para negociar essa semana. Quer que eu tente uma condição melhor para você?"),
    ],
  },
  {
    id: "jornada-pos-negativa",
    categoria: "jornada",
    resumo: "Recontato pós-negativa: respeita o \"não\" agora, mantém a porta aberta e volta no tempo certo.",
    fluxo: {
      nome: "Recontato pós-negativa — voltar no tempo certo",
      descricao: "Para quem disse não ou pediu para adiar a decisão.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 30,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
      segmentoEstagios: ["pediu_tempo", "desistiu"],
    },
    etapas: [
      wa(1, 0, "Registro do não", "{{primeiro_nome}}, respeito totalmente sua decisão de pausar agora. Deixo seu cadastro guardado e volto só quando aparecer algo realmente relevante, combinado?"),
      wa(2, 30, "Mudou algo?", "Oi {{primeiro_nome}}, passou um mês desde a nossa conversa. Mudou algo no seu planejamento ou seguimos aguardando?"),
      mail(3, 75, "O que mudou no mercado", "Olá {{nome}},\n\nDesde nossa última conversa o mercado mudou: novos lançamentos, ajustes de preço e condições de financiamento diferentes.\n\nSe quiser, preparo um resumo sem compromisso."),
      wa(4, 120, "Porta aberta", "{{primeiro_nome}}, continuo à disposição. Se quiser retomar a busca ou indicar alguém, é só me chamar por aqui."),
    ],
  },
  {
    id: "jornada-nao-responde",
    categoria: "jornada",
    resumo: "Troca para \"não responde\": tentativa por outro canal, pergunta simples de sim/não e encerramento educado.",
    fluxo: {
      nome: "Lead sem retorno — última tentativa multicanal",
      descricao: "Leads marcados como sem resposta no pipeline.",
      publicoAlvo: "lead_sem_resposta",
      diasInatividade: 10,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: true,
      segmentoEstagios: ["nao_responde"],
    },
    etapas: [
      wa(1, 0, "Pergunta simples", "{{primeiro_nome}}, só preciso de um sim ou não: sua busca por imóvel ainda está de pé?"),
      mail(2, 4, "Tentativa por e-mail", "Olá {{nome}},\n\nTentei falar com você pelo WhatsApp e não consegui retorno. Se preferir, respondo tudo por aqui mesmo: basta me dizer o que procura.\n\nSe não faz mais sentido agora, me avise que encerro os contatos."),
      wa(3, 10, "Encerramento educado", "{{primeiro_nome}}, vou pausar os contatos por aqui para não incomodar. Quando quiser retomar, é só me chamar que sigo com seu histórico salvo."),
    ],
  },
  {
    id: "jornada-aniversario-busca",
    categoria: "jornada",
    resumo: "Um ano da primeira conversa: retrospectiva do mercado e convite para reavaliar o momento de comprar.",
    fluxo: {
      nome: "Um ano de cadastro — reavaliar o momento",
      descricao: "Toque anual para leads antigos que nunca fecharam.",
      publicoAlvo: "lead_inativo",
      diasInatividade: 180,
      canal: "whatsapp",
      encerrarAoResponder: true,
      ativo: false,
    },
    etapas: [
      wa(1, 0, "Faz tempo que conversamos", "Oi {{primeiro_nome}}, faz um bom tempo desde a nossa primeira conversa sobre imóveis. Esse assunto ainda está nos seus planos?"),
      mail(2, 15, "Retrospectiva do mercado", "Olá {{nome}},\n\nPreparei um panorama do que mudou no último ano na região que você acompanhava: preços, oferta e prazo médio de venda.\n\nSe quiser retomar a busca, começo por onde paramos."),
      wa(3, 45, "Simulação atualizada", "{{primeiro_nome}}, as condições de financiamento mudaram. Quer que eu refaça sua simulação com os números de hoje?"),
    ],
  },
];
