/**
 * Copyright (c) Visão Business. Todos os direitos reservados.
 * VB Solution CRM — propriedade intelectual da Visão Business.
 * Uso conforme LICENSE na raiz do repositório.
 */

/** Writable camelCase fields for realty_contratos (store/update pick lists). */
export const CONTRATO_FIELD_KEYS = [
  "title",
  "status",
  "value",
  "startDate",
  "endDate",
  "notes",
  "imovelId",
  "proprietarioId",
  "leadSaleId",
  "propostaId",
  "cliente",
  "clienteTelefone",
  "clienteCpf",
  "clienteEmail",
  "clienteRg",
  "tipo",
  "inquilino",
  "proprietario",
  "contratoUrl",
  "vistoriaEntrada",
  "vistoriaVideo",
  "apoliceSeguro",
  "matricula",
  "indiceCorrecao",
  "percentualCorrecao",
  "dataProximaCorrecao",
  "diaVencimentoAluguel",
  "dataVencimentoApolice",
  "tipoGarantia",
  "contratoAnexoUrl",
  "apoliceAnexoUrl",
  "vistoriaAnexoUrl",
  "numeroAgua",
  "numeroLuz",
  "inscricaoIptu",
  "canalOrigem",
  "proprietarioTelefone",
  "proprietarioCpf",
  "proprietarioEmail",
  "proprietarioRg",
  "proprietarioBanco",
  "proprietarioAgencia",
  "proprietarioConta",
  "proprietarioPix",
  "comissaoPercentual",
  "comissaoValor",
  "comissaoTipo",
  "temParceria",
  "parceiroNome",
  "parceiroComissaoPercentual",
  "parceiroComissaoValor",
  "captadorNome",
  "captadorTelefone",
  "captadorComissaoPercentual",
  "captadorComissaoValor",
  "impostoTipo",
  "impostoPercentual",
  "impostoValor",
  "corretorNome",
  "corretorComissaoPercentual",
  "corretorComissaoValor",
  "corretorId",
  "valorIptu",
  "iptuParcelado",
  "valorCondominio",
  "condominioInclui",
  "inquilinoTelefone",
  "inquilinoCpf",
  "inquilinoEmail",
  "inquilinoRg",
  "inquilino2Nome",
  "inquilino2Cpf",
  "inquilino2Telefone",
  "inquilino2Email",
  "inquilino2Rg",
  "caucaoValor",
  "caucaoQuantidade",
  "conjugeProprietario",
  "conjugeCpf",
  "conjugeTelefone",
  "conjugeEmail",
  "aditivoAnexoUrl",
  "seguroIncendioAnexoUrl",
  "seguroFiancaAnexoUrl",
  "fiadorNome",
  "fiadorCpf",
  "fiadorTelefone",
  "fiadorEmail",
  "fiadorEstadoCivil",
  "fiadorEndereco",
  "fiadorMatriculaUrl",
  "fiadorRendaUrl",
  "fiador2Nome",
  "fiador2Cpf",
  "fiador2Telefone",
  "fiador2Email",
  "fiador2EstadoCivil",
  "fiador2Endereco",
  "fiador2MatriculaUrl",
  "fiador2RendaUrl",
  "vistoriaVideoUrl",
  "caucaoComprovanteUrl",
  "comprovanteAguaUrl",
  "comprovanteLuzUrl",
  "numeroUnidade",
  "parceriaEnvolvidos",
  "codigoContrato"
] as const;

export type ContratoFieldKey = (typeof CONTRATO_FIELD_KEYS)[number];

export const CONTRATO_NULLABLE_INT_KEYS = [
  "imovelId",
  "proprietarioId",
  "leadSaleId",
  "propostaId",
  "corretorId",
  "diaVencimentoAluguel",
  "caucaoQuantidade"
] as const;

export const CONTRATO_BOOLEAN_KEYS = [
  "vistoriaEntrada",
  "vistoriaVideo",
  "apoliceSeguro",
  "temParceria",
  "iptuParcelado"
] as const;

export const CONTRATO_SEARCH_FIELDS = [
  "title",
  "cliente",
  "inquilino",
  "proprietario",
  "corretorNome",
  "codigoContrato",
  "matricula",
  "notes",
  "status",
  "tipo"
] as const;
