/**
 * Copyright (c) Visão Business. Todos os direitos reservados.
 * VB Solution CRM — propriedade intelectual da Visão Business.
 * Uso conforme LICENSE na raiz do repositório.
 */

/** Class names for Brain.AI shell (replaces MUI makeStyles). */
export const b = {
  root: "brain-shell brain-shell__root",
  rootEmbedded: "brain-shell brain-shell__root brain-shell__root--embedded",
  sidebar: "brain-shell__sidebar",
  sidebarCollapsed: "brain-shell__sidebar--collapsed",
  sidebarHeader: "brain-shell__sidebar-header",
  sidebarBrandLogo: "brain-shell__sidebar-brand-logo",
  sidebarBrandRow: "brain-shell__sidebar-brand-row",
  sidebarBrandName: "brain-shell__sidebar-brand-name",
  sidebarCollapseBtn: "brain-shell__sidebar-collapse-btn",
  sidebarMenu: "brain-shell__sidebar-menu",
  sidebarMenuItem: "brain-shell__sidebar-menu-item",
  sidebarMenuItemActive: "brain-shell__sidebar-menu-item--active",
  sidebarMenuItemLabel: "brain-shell__sidebar-menu-item-label",
  sidebarSectionLabel: "brain-shell__sidebar-section-label",
  sidebarRecentSection: "brain-shell__sidebar-recent-section",
  sidebarRecentList: "brain-shell__sidebar-recent-list",
  sidebarEmpty: "brain-shell__sidebar-empty",
  conversationRecentRow: "brain-shell__conversation-recent-row",
  conversationRecentItemActive: "brain-shell__conversation-recent-row--active",
  conversationRecentTitle: "brain-shell__conversation-recent-title",
  conversationRecentActions: "brain-shell__conversation-recent-actions",
  conversationRecentActionBtn: "brain-shell__conversation-recent-action-btn",
  conversationRecentEditInput: "brain-shell__conversation-recent-edit-input",
  mainContent: "brain-shell__main-content",
  mainContentConversation: "brain-shell__main-content--conversation",
  mainContentPlans: "brain-shell__main-content--plans",
  mainContentChat: "brain-shell__main-content--chat",
  mainContentVoice: "brain-shell__main-content--voice",
  mainContentIde: "brain-shell__main-content--ide",
  brandGradient: "brain-shell__brand-gradient",
  idePage: "brain-shell__ide-page",
  idePageHome: "brain-shell__ide-page--home",
  welcomeContainer: "brain-shell__welcome-container",
  greetingTitle: "brain-shell__greeting-title",
  welcomeComposerBlock: "brain-shell__welcome-composer-block",
  inputContainer: "brain-shell__input-container",
  composerStack: "brain-shell__composer-stack",
  composerShell: "brain-shell__composer-shell",
  mcpChipRow: "brain-shell__mcp-chip-row",
  inputBox: "brain-shell__input-box",
  textArea: "brain-shell__text-area",
  inputFooter: "brain-shell__input-footer",
  inputFooterLeft: "brain-shell__input-footer-left",
  inputFooterRight: "brain-shell__input-footer-right",
  modelSelectorWrap: "brain-shell__model-selector-wrap",
  modelSelector: "brain-shell__model-selector",
  modelSelectorOpen: "brain-shell__model-selector--open",
  iconBtn: "brain-shell__icon-btn",
  plusMenuAnchor: "brain-shell__plus-menu-anchor",
  iconBtnRecording: "brain-shell__icon-btn brain-shell__icon-btn--recording",
  sendBtn: "brain-shell__send-btn",
  connectorIconsRow: "brain-shell__connector-icons-row",
  connectorIconBtn: "brain-shell__connector-icon-btn",
  toolChip: "brain-shell__tool-chip",
  voiceRecordingBar: "brain-shell__voice-recording-bar",
  voiceRecordingDot: "brain-shell__voice-recording-dot",
  voiceIconBtn: "brain-shell__voice-icon-btn",
  voiceIconBtnSave: "brain-shell__voice-icon-btn brain-shell__voice-icon-btn--save",
  voiceIconBtnCancel: "brain-shell__voice-icon-btn brain-shell__voice-icon-btn--cancel",
  quickActionsGrid: "brain-shell__quick-actions-grid",
  quickActionCard: "brain-shell__quick-action-card",
  quickActionIcon: "brain-shell__quick-action-icon",
  quickActionTitle: "brain-shell__quick-action-title",
  chatContainer: "brain-shell__chat-container",
  chatHeader: "brain-shell__chat-header",
  chatHeaderBrand: "brain-shell__chat-header-brand",
  chatHeaderRight: "brain-shell__chat-header-right",
  chatHeaderTools: "brain-shell__chat-header-tools",
  chatHeaderActionsPlain: "brain-shell__chat-header-actions-plain",
  helpBtnPlain: "brain-shell__help-btn-plain",
  modelBadge: "brain-shell__model-badge",
  chatHeaderSep: "brain-shell__chat-header-sep",
  chatHeaderTitle: "brain-shell__chat-header-title",
  messagesArea: "brain-shell__messages-area",
  messageRow: "brain-shell__message-row",
  messageRowUser: "brain-shell__message-row brain-shell__message-row--user",
  messageRowUserInner: "brain-shell__message-row-user-inner",
  messageUserHeader: "brain-shell__message-user-header",
  messageUserActions: "brain-shell__message-user-actions",
  messageActionBtn: "brain-shell__message-action-btn",
  messageRowAssistant: "brain-shell__message-row brain-shell__message-row--assistant",
  messageLabel: "brain-shell__message-label",
  messageLabelUser: "brain-shell__message-label brain-shell__message-label--user",
  messageLabelAssistant: "brain-shell__message-label brain-shell__message-label--assistant",
  messageContent: "brain-shell__message-content",
  messageContentUser: "brain-shell__message-content brain-shell__message-content--user",
  messageContentAssistant: "brain-shell__message-content brain-shell__message-content--assistant",
  toolBadge: "brain-shell__tool-badge",
  typingIndicator: "brain-shell__typing-indicator",
  workingBar: "brain-shell__working-bar",
  bottomInput: "brain-shell__bottom-input",
  bottomInputMenuOpen: "brain-shell__bottom-input--menu-open",
  modelPickerDropdown: "brain-shell__model-picker-dropdown",
  modelPickerSection: "brain-shell__model-picker-section",
  modelPickerProviderRow: "brain-shell__model-picker-provider-row",
  modelPickerProviderLabel: "brain-shell__model-picker-provider-label",
  modelPickerItem: "brain-shell__model-picker-item",
  modelPickerItemActive: "brain-shell__model-picker-item--active",
  modelPickerItemBody: "brain-shell__model-picker-item-body",
  modelPickerItemName: "brain-shell__model-picker-item-name",
  modelPickerItemDesc: "brain-shell__model-picker-item-desc",
  modelPickerDivider: "brain-shell__model-picker-divider",
  modelMenuItem: "brain-shell__model-menu-item",
  fileModal: "brain-shell__file-sheet brain-sheet",
  fileModalHeader: "brain-shell__file-modal-header",
  fileModalTitle: "brain-shell__file-modal-title",
  fileModalContent: "brain-shell__file-modal-content",
  fileModalPre: "brain-shell__file-modal-pre",
  fileModalTable: "brain-shell__file-modal-table",
  downloadBtn: "brain-shell__download-btn",
  fileModalFooter: "brain-shell__file-modal-footer",
  attachLibraryBtn: "brain-shell__attach-library-btn",
  attachLibraryBadge: "brain-shell__attach-library-badge",
  libraryModal: "brain-shell__library-sheet brain-sheet",
  libraryItem: "brain-shell__library-item",
  libraryItemIcon: "brain-shell__library-item-icon",
  libraryItemInfo: "brain-shell__library-item-info",
  libraryItemTitle: "brain-shell__library-item-title",
  libraryItemMeta: "brain-shell__library-item-meta",
  libraryEmpty: "brain-shell__library-empty",
  librarySection: "brain-shell__library-section",
  voiceModeBtn: "brain-shell__voice-mode-btn",
  voiceModeBtnActive: "brain-shell__voice-mode-btn brain-shell__voice-mode-btn--active",
  iconBtnPlain: "brain-shell__icon-btn-plain",
  loadingCenter: "brain-shell__loading-center",
};

export default b;
