/**
 * Copyright (c) Visão Business. Todos os direitos reservados.
 * VB Solution CRM — propriedade intelectual da Visão Business.
 * Uso conforme LICENSE na raiz do repositório.
 */

/** Subpage + menu + dialog class names (Brain.AI views). */
export const s = {
  root: "brain-sub__root",
  inner: "brain-sub__inner",
  innerWide: "brain-sub__inner brain-sub__inner--wide",
  header: "brain-sub__header",
  headerRow: "brain-sub__header-row",
  title: "brain-sub__title",
  lead: "brain-sub__lead",
  actions: "brain-sub__actions",
  btnGhost: "brain-sub__btn brain-sub__btn--ghost",
  btnPrimary: "brain-sub__btn brain-sub__btn--primary",
  btnDark: "brain-sub__btn brain-sub__btn--dark",
  searchWrap: "brain-sub__search-wrap",
  searchIcon: "brain-sub__search-icon",
  searchInput: "brain-sub__search-input",
  clearBtn: "brain-sub__clear-btn",
  list: "brain-sub__list",
  row: "brain-sub__row",
  rowActive: "brain-sub__row--active",
  rowTitle: "brain-sub__row-title",
  rowDate: "brain-sub__row-date",
  empty: "brain-sub__empty",
  loading: "brain-sub__loading",
  grid: "brain-sub__grid",
  grid2: "brain-sub__grid brain-sub__grid--2",
  card: "brain-sub__card",
  cardActive: "brain-sub__card--active",
  cardTop: "brain-sub__card-top",
  cardBrand: "brain-sub__card-brand",
  cardIcon: "brain-sub__card-icon",
  cardTitle: "brain-sub__card-title",
  cardProvider: "brain-sub__card-provider",
  cardDesc: "brain-sub__card-desc",
  cardMeta: "brain-sub__card-meta",
  check: "brain-sub__check",
  checkOn: "brain-sub__check--on",
  saveBar: "brain-sub__save-bar",
  section: "brain-sub__section",
  sectionTitle: "brain-sub__section-title",
  optionGrid: "brain-sub__option-grid",
  optionCard: "brain-sub__option-card",
  optionCardActive: "brain-sub__option-card--active",
  optionLabel: "brain-sub__option-label",
  optionHint: "brain-sub__option-hint",
  field: "brain-sub__field",
  fieldLabel: "brain-sub__field-label",
  textarea: "brain-sub__textarea",
  input: "brain-sub__input",
  switchRow: "brain-sub__switch-row",
  preview: "brain-sub__preview",
  menuOverlay: "brain-menu__overlay",
  menuPanel: "brain-menu__panel",
  menuRow: "brain-menu__row",
  menuRowIcon: "brain-menu__row-icon",
  menuRowRight: "brain-menu__row-right",
  menuDivider: "brain-menu__divider",
  dialogTitle: "brain-sub__dialog-title",
  dialogLead: "brain-sub__dialog-lead",
  voicePanel: "brain-voice__panel",
  voiceHeader: "brain-voice__header",
  voiceTitle: "brain-voice__title",
  voiceOrb: "brain-voice__orb",
  voiceGenderOptions: "brain-voice__gender-options",
  voiceGenderOption: "brain-voice__gender-option",
};

export default s;
