// Estados do Brasil + capitais e principais cidades
export const ESTADOS_BRASIL: { uf: string; nome: string; cidades: string[] }[] = [
  { uf: "AC", nome: "Acre", cidades: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira"] },
  { uf: "AL", nome: "Alagoas", cidades: ["Maceió", "Arapiraca", "Palmeira dos Índios"] },
  { uf: "AP", nome: "Amapá", cidades: ["Macapá", "Santana", "Laranjal do Jari"] },
  { uf: "AM", nome: "Amazonas", cidades: ["Manaus", "Parintins", "Itacoatiara"] },
  { uf: "BA", nome: "Bahia", cidades: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna", "Ilhéus", "Lauro de Freitas"] },
  { uf: "CE", nome: "Ceará", cidades: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral"] },
  { uf: "DF", nome: "Distrito Federal", cidades: ["Brasília", "Taguatinga", "Ceilândia", "Águas Claras", "Sobradinho", "Gama", "Guará", "Samambaia", "Planaltina", "Núcleo Bandeirante"] },
  { uf: "ES", nome: "Espírito Santo", cidades: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares"] },
  { uf: "GO", nome: "Goiás", cidades: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Valparaíso de Goiás", "Águas Lindas de Goiás"] },
  { uf: "MA", nome: "Maranhão", cidades: ["São Luís", "Imperatriz", "Caxias", "Timon"] },
  { uf: "MT", nome: "Mato Grosso", cidades: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop"] },
  { uf: "MS", nome: "Mato Grosso do Sul", cidades: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá"] },
  { uf: "MG", nome: "Minas Gerais", cidades: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba", "Sete Lagoas"] },
  { uf: "PA", nome: "Pará", cidades: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal"] },
  { uf: "PB", nome: "Paraíba", cidades: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos"] },
  { uf: "PR", nome: "Paraná", cidades: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu"] },
  { uf: "PE", nome: "Pernambuco", cidades: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista"] },
  { uf: "PI", nome: "Piauí", cidades: ["Teresina", "Parnaíba", "Picos"] },
  { uf: "RJ", nome: "Rio de Janeiro", cidades: ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Belford Roxo", "Campos dos Goytacazes", "Petrópolis", "Volta Redonda"] },
  { uf: "RN", nome: "Rio Grande do Norte", cidades: ["Natal", "Mossoró", "Parnamirim"] },
  { uf: "RS", nome: "Rio Grande do Sul", cidades: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí", "Novo Hamburgo"] },
  { uf: "RO", nome: "Rondônia", cidades: ["Porto Velho", "Ji-Paraná", "Ariquemes"] },
  { uf: "RR", nome: "Roraima", cidades: ["Boa Vista", "Rorainópolis"] },
  { uf: "SC", nome: "Santa Catarina", cidades: ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Itajaí", "Criciúma", "Balneário Camboriú"] },
  { uf: "SP", nome: "São Paulo", cidades: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "Ribeirão Preto", "Sorocaba", "São José dos Campos", "Santos", "Mauá", "São José do Rio Preto", "Mogi das Cruzes", "Diadema", "Jundiaí", "Piracicaba", "Bauru"] },
  { uf: "SE", nome: "Sergipe", cidades: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto"] },
  { uf: "TO", nome: "Tocantins", cidades: ["Palmas", "Araguaína", "Gurupi"] },
];

// Bairros de Brasília / DF (RAs e principais bairros)
export const BAIRROS_BRASILIA: string[] = [
  "Asa Sul", "Asa Norte", "Lago Sul", "Lago Norte", "Sudoeste", "Octogonal", "Noroeste",
  "Cruzeiro Velho", "Cruzeiro Novo", "Park Way", "Setor de Indústrias Gráficas (SIG)",
  "Setor Comercial Sul", "Setor Comercial Norte", "Setor Bancário Sul", "Setor Hoteleiro Sul",
  "Vila Planalto", "Vila Telebrasília",
  // RAs comuns
  "Águas Claras", "Taguatinga Centro", "Taguatinga Norte", "Taguatinga Sul",
  "Ceilândia Centro", "Ceilândia Norte", "Ceilândia Sul", "Sol Nascente", "Pôr do Sol",
  "Samambaia Norte", "Samambaia Sul",
  "Guará I", "Guará II", "Park Sul",
  "Sobradinho I", "Sobradinho II", "Grande Colorado",
  "Planaltina", "Arapoanga", "Vale do Amanhecer",
  "Riacho Fundo I", "Riacho Fundo II",
  "Recanto das Emas", "Santa Maria", "Gama Leste", "Gama Oeste",
  "Núcleo Bandeirante", "Candangolândia",
  "São Sebastião", "Jardim Botânico", "Itapoã", "Paranoá",
  "Vicente Pires", "Arniqueira",
  "Brazlândia", "Estrutural (SCIA)",
];
