import { describe, expect, it } from "vitest";

import { buildContratoExportRows, parseContratoText } from "./contratosSpreadsheet";
import type { Contrato } from "@/hooks/useContratos";

describe("contratosSpreadsheet", () => {
  it("importa contratos a partir de CSV com cabeçalhos exportados", () => {
    const csv = [
      "Título;Cliente;Tipo;Status;Valor;Comissão %;Comissão R$;Início;Fim;Proprietário;Canal Origem",
      "Contrato Centro;João Silva;Locação;Ativo;3500,00;10;350,00;01/04/2026;31/03/2027;Maria Souza;Instagram",
    ].join("\n");

    const { items, errors } = parseContratoText(csv);

    expect(errors).toEqual([]);
    expect(items).toHaveLength(1);
    expect(items[0]).toMatchObject({
      titulo: "Contrato Centro",
      cliente: "João Silva",
      tipo: "Locação",
      status: "ativo",
      valor: 3500,
      comissao_percentual: 10,
      comissao_valor: 350,
      data_inicio: "2026-04-01",
      data_fim: "2027-03-31",
      proprietario: "Maria Souza",
      canal_origem: "instagram",
    });
  });

  it("gera linhas de exportação compatíveis com reimportação", () => {
    const contrato = {
      id: "1",
      imobiliaria_id: "imob-1",
      titulo: "Contrato Jardins",
      cliente: "Cliente Teste",
      cliente_telefone: "",
      cliente_cpf: "",
      cliente_email: "",
      tipo: "Venda",
      valor: 820000,
      status: "rascunho",
      data_inicio: "2026-05-10",
      data_fim: null,
      imovel_id: null,
      corretor_id: null,
      inquilino: null,
      proprietario: "Maria",
      contrato_url: null,
      vistoria_entrada: false,
      vistoria_video: false,
      apolice_seguro: false,
      observacoes: "teste",
      created_at: "",
      updated_at: "",
      matricula: "123",
      proprietario_id: null,
      indice_correcao: null,
      percentual_correcao: null,
      data_proxima_correcao: null,
      dia_vencimento_aluguel: null,
      data_vencimento_apolice: null,
      tipo_garantia: null,
      contrato_anexo_url: null,
      apolice_anexo_url: null,
      vistoria_anexo_url: null,
      numero_agua: null,
      numero_luz: null,
      inscricao_iptu: null,
      canal_origem: "instagram",
      proprietario_telefone: null,
      proprietario_cpf: null,
      comissao_percentual: 6,
      comissao_valor: 49200,
      tem_parceria: false,
      parceiro_nome: null,
      parceiro_comissao_percentual: null,
      parceiro_comissao_valor: null,
      captador_nome: null,
      captador_telefone: null,
      captador_comissao_percentual: null,
      captador_comissao_valor: null,
      imposto_tipo: null,
      imposto_percentual: null,
      imposto_valor: null,
      corretor_nome: "Ana",
      corretor_comissao_percentual: null,
      corretor_comissao_valor: 10000,
      valor_iptu: null,
      iptu_parcelado: false,
      valor_condominio: null,
      condominio_inclui: null,
      inquilino_telefone: null,
      inquilino_cpf: null,
      caucao_valor: null,
      caucao_quantidade: null,
      aditivo_anexo_url: null,
      seguro_incendio_anexo_url: null,
      seguro_fianca_anexo_url: null,
      fiador_nome: null,
      fiador_cpf: null,
      fiador_telefone: null,
      fiador_email: null,
      fiador_estado_civil: null,
      fiador_endereco: null,
      numero_unidade: "1201",
      conjuge_proprietario: null,
      conjuge_cpf: null,
      conjuge_telefone: null,
      conjuge_email: null,
      inquilino_email: null,
      inquilino2_nome: null,
      inquilino2_cpf: null,
      inquilino2_telefone: null,
      inquilino2_email: null,
      parceria_envolvidos: null,
      vistoria_video_url: null,
      caucao_comprovante_url: null,
      fiador_matricula_url: null,
      fiador_renda_url: null,
      fiador2_nome: null,
      fiador2_cpf: null,
      fiador2_telefone: null,
      fiador2_email: null,
      fiador2_estado_civil: null,
      fiador2_endereco: null,
      fiador2_matricula_url: null,
      fiador2_renda_url: null,
      comprovante_agua_url: null,
      comprovante_luz_url: null,
      cliente_rg: null,
      proprietario_email: null,
      proprietario_rg: null,
      proprietario_banco: null,
      proprietario_agencia: null,
      proprietario_conta: null,
      proprietario_pix: null,
      inquilino_rg: null,
      inquilino2_rg: null,
      comissao_tipo: null,
      codigo_contrato: null,
    } satisfies Contrato;

    const [row] = buildContratoExportRows([contrato]);

    expect(row).toMatchObject({
      titulo: "Contrato Jardins",
      status: "Rascunho",
      canal_origem: "Instagram",
      comissao_valor: 49200,
      corretor_nome: "Ana",
    });
  });
});